"""AUTO-GENERATED - do not edit by hand.

Regenerate with:  python tools/import_meder.py voicerx/terms_imported.py

Clinical terms imported from the MedER Bengali/English dataset.
These are MACHINE-IMPORTED and have NOT been clinically reviewed -
a lower trust tier than the curated CLINICAL_TERMS in glossary.py.
They are used only to RULE THINGS OUT (a term here can never be a
medication), which is the safe direction for unreviewed data.

raw candidate pairs seen : 12486
survived cleaning        : 2525
english canonical terms  : 2067
dropped for colliding with a drug/lab : 33

collisions dropped (these would have shadowed a real drug):
    active vitamin d / সক্রিয় ভিটামিন ডি - folds onto drug Vitamin D3
    amoxicillin / - - english side is a drug
    anti-insulin effects / ইনসুলিন বিরোধী প্রভাব - folds onto drug Human insulin
    blood test / রক্ত পরীক্ষা - folds onto lab blood test (unspecified)
    calcium / ক্যালসিয়াম - folds onto drug Calcium carbonate
    calcium concentration / ক্যালসিয়াম ঘনত্ব - folds onto drug Calcium carbonate
    calcium content / ক্যালসিয়ামের পরিমাণ - folds onto drug Calcium carbonate
    calcium deficiency / ক্যালসিয়ামের ঘাটতি - folds onto drug Calcium carbonate
    calcium levels / ক্যালসিয়ামের মাত্রা - folds onto drug Calcium carbonate
    calcium release / ক্যালসিয়াম মুক্তি - folds onto drug Calcium carbonate
    ct scan / সিটি স্ক্যান - folds onto lab CT scan
    cytoplasmic calcium / সাইটোপ্লাজমিক ক্যালসিয়াম - folds onto drug Calcium carbonate
    diazepam / - - english side is a drug
    ecg / ইসিজি - folds onto lab ECG
    fexofenadine / - - english side is a drug
    insulin / ইনসুলিন - folds onto drug Human insulin
    insulin resistance / ইনসুলিন রেজিস্ট্যান্স - folds onto drug Human insulin
    insulin sensitivity / ইনসুলিন সংবেদনশীলতা - folds onto drug Human insulin
    insulin-like / ইনসুলিন-লাইক - folds onto drug Human insulin
    insulin-like growth factor / ইনসুলিন-সদৃশ বৃদ্ধির কারণ - folds onto drug Human insulin
    ionic calcium / আয়নিক ক্যালসিয়াম - folds onto drug Calcium carbonate
    lipids / লিপিড - folds onto lab Lipid profile
    montelukast / - - english side is a drug
    serum calcium / সিরাম ক্যালসিয়াম - folds onto drug Calcium carbonate
    serum calcium level / সিরাম ক্যালসিয়াম স্তর - folds onto drug Calcium carbonate
    serum ionized calcium / সিরাম আয়নিত ক্যালসিয়াম - folds onto drug Calcium carbonate
    spironolactone / - - english side is a drug
    ultrasound / আল্ট্রাসাউন্ড - folds onto lab USG
    urea transporter cells / ইউরিয়া পরিবহনকারীদের কোষ - folds onto lab Urea
    vitamin b / ভিটামিন বি - folds onto drug Vitamin B complex
    vitamin b complex / - - english side is a drug
    vitamin d / ভিটামিন ডি - folds onto drug Vitamin D3
    vitamin d activation / ভিটামিন ডি সক্রিয়করণ - folds onto drug Vitamin D3
"""

IMPORTED_TERMS: dict[str, tuple[str, ...]] = {
    "a throat infection": ("গলার সংক্রমণ",),
    "abdomen": ("উদর",),
    "abdominal colic": ("এব্ডোমিনাল কলিক",),
    "abdominal discomfort": ("তলপেটের অস্বস্তি",),
    "abdominal pain": ("তলপেটে ব্যথা", "পেট ব্যথা", "পেটে ব্যথা", "পেটে ব্যথা হতে পারে।", "পেটে ব্যাথা",),
    "abnormal hormone formation": ("অস্বাভাবিক হরমোন গঠন",),
    "abnormal liver function": ("অস্বাভাবিক লিভারের কার্যকলাপ",),
    "abnormal menstrual cycles": ("অস্বাভাবিক মাসিক চক্র",),
    "abnormalities": ("অস্বাভাবিকতা",),
    "abortion": ("এবরশন", "গর্ভস্রাব",),
    "abscess": ("ফোড়া",),
    "absence of menstruation": ("ঋতুস্রাবের অনুপস্থিতি",),
    "absorption": ("শোষণ",),
    "acceleration hormone": ("কর্ম ত্বরাণ্বিতকরণ হরমোন",),
    "acid": ("অ্যাসিড",),
    "acid reflux": ("অ্যাসিড রিফ্লাক্স",),
    "acne": ("ব্রণ",),
    "acne vulgaris": ("ব্রণ ভালগারিস", "ভালগারিস",),
    "acquired": ("অর্জিত।",),
    "acromegaly": ("অ্যাক্রোমেগালি", "অ্যাক্রোমেগালি।",),
    "acting centrally": ("কেন্দ্রীয়ভাবে কাজ করা",),
    "action": ("ক্রিয়া",),
    "activated charcoal": ("অ্যাক্টিভেটেড চারকোল", "একটিভেটেড চারকোল",),
    "activation": ("সক্রিয়করণ।",),
    "active form": ("সক্রিয় রূপ",),
    "active metabolite": ("সক্রিয় বিপাক",),
    "active substance": ("সক্রিয় পদার্থ",),
    "activities": ("ক্রিয়াকলাপ",),
    "activity": ("কার্যকলাপ",),
    "acute hypotension": ("তীব্র হাইপোটেনশন",),
    "acute kidney injury": ("তীব্র কিডনি আঘাত",),
    "acute mania": ("তীব্র ম্যানিয়া",),
    "acute renal failure": ("তীব্র রেনাল ব্যর্থতা",),
    "addiction": ("আসক্তি", "নেশা",),
    "addison's disease": ("অ্যাডিসন ডিজিজ", "অ্যাডিসনের রোগ",),
    "additional dosage": ("অতিরিক্ত ডোজ",),
    "adenoma": ("অ্যাডেনোমা",),
    "adenomas": ("অ্যাডিনোমা", "অ্যাডেনোমা",),
    "adenosine monophosphate": ("এডিনোসিন মনোফসফেট",),
    "adequate concentration": ("পর্যাপ্ত ঘনত্ব",),
    "adhd": ("এডিএইচডি",),
    "adherent placenta": ("এডহেরেন্ট প্লাসেন্টা",),
    "adhesive plaster": ("আঠালো প্লাস্টার",),
    "adipose tissue": ("অ্যাডিপোজ টিস্যু",),
    "administration": ("প্রশাসন",),
    "adrenal": ("অ্যাড্রিনাল",),
    "adrenal atropy": ("অ্যাড্রিনাল এট্রপি",),
    "adrenal cortex": ("অ্যাড্রিনাল কর্টেক্স", "অ্যাড্রিনাল কর্টেক্সে", "অ্যাড্রিনাল কর্টেক্সের",),
    "adrenal gland": ("অ্যাড্রিনাল গ্রন্থি", "অ্যাড্রেনাল গ্রন্থি",),
    "adrenal gland disorders": ("অ্যাড্রেনাল গ্রন্থি ব্যাধি",),
    "adrenal glands": ("অ্যাড্রিনাল গ্রন্থি", "এড্রিনাল গ্রন্থি",),
    "adrenal insufficiency": ("অ্যাড্রিনাল অপ্রতুলতা",),
    "adrenal medulla": ("অ্যাড্রিনাল মেডুলা",),
    "adrenalectomy": ("অ্যাড্রেনালেক্টমি",),
    "adrenaline": ("অ্যাড্রেনালিন",),
    "adrenaline levels": ("অ্যাড্রেনালিনের মাত্রা",),
    "adrenals": ("অ্যাড্রেনাল", "অ্যাড্রেনালস",),
    "adrenoceptor": ("অ্যাড্রেনোসেপ্টর",),
    "adult size": ("প্রাপ্তবয়স্ক আকার।",),
    "adulthood": ("প্রাপ্তবয়স্ক",),
    "adults": ("প্রাপ্তবয়স্ক",),
    "adverse effects": ("প্রতিকূল প্রভাব", "বিপরীত প্রভাব।", "বিরূপ প্রভাব",),
    "adverse reactions": ("বিরূপ প্রতিক্রিয়া",),
    "advice": ("পরামর্শ",),
    "affected": ("প্রভাবিত",),
    "age": ("বয়স",),
    "agents used": ("ব্যবহৃত এজেন্ট",),
    "aggression": ("আগ্রাসন",),
    "aggressive response": ("আক্রমণাত্মক প্রতিক্রিয়া",),
    "aggressive-impulsive disorder": ("আক্রমনাত্মক-ইম্পলসিভ ডিসঅর্ডার",),
    "agoraphobia": ("অ্যাগোরাফোবিয়া", "অ্যাগ্রোফোবিয়া",),
    "agranulocytosis": ("অ্যাগ্রানুলোসাইটোসিস",),
    "aids": ("এইডস",),
    "airway": ("শ্বাসনালী",),
    "airways": ("শ্বাসনালী",),
    "akathisia": ("অ্যাকাথিসিয়া",),
    "alcohol": ("অ্যালকোহল",),
    "alcohol interactions": ("অ্যালকোহল মিথস্ক্রিয়া",),
    "aldosterone": ("অ্যালডোস্টেরন",),
    "alkalosis": ("অ্যালকালোসিস",),
    "allergens": ("অ্যালার্জেন",),
    "allergic": ("অ্যালার্জিক",),
    "allergic conjunctivitis": ("অ্যালার্জিক কনজেক্টিভাইটিস",),
    "allergic reaction": ("অ্যালার্জির প্রতিক্রিয়া", "এলার্জি প্রতিক্রিয়া",),
    "allergic reactions": ("অ্যালার্জি প্রতিক্রিয়া", "অ্যালার্জির প্রতিক্রিয়া",),
    "allergic rhinitis": ("অ্যালার্জিক রাইনাইটিস",),
    "allergies": ("অ্যালার্জি", "অ্যালার্জির", "এলার্জি",),
    "allergy": ("অ্যালার্জি", "অ্যাালার্জি", "এলার্জি", "এলার্জি‌", "লার্জি",),
    "allergy symptoms": ("অ্যালার্জি লক্ষণ",),
    "allergy/inflammation": ("এলার্জি/প্রদাহ",),
    "alternative splicing": ("বিকল্প স্প্লিসিং",),
    "alternatives": ("বিকল্প",),
    "alveolar ducts": ("অ্যালভিওলার নালী",),
    "alzheimer's": ("আলঝেইমার",),
    "amenorrhea": ("অ্যামেনোরিয়া",),
    "amino acid": ("অ্যামিনো অ্যাসিড",),
    "amygdala": ("অ্যামিগডালা",),
    "anabolic": ("অ্যানাবলিক",),
    "analgesia": ("অ্যানালজেসিয়া",),
    "anaphylaxis": ("অ্যানাফিল্যাক্সিস",),
    "and chills": ("এবং ঠান্ডা",),
    "and complications with sexual function": ("এবং যৌন ফাংশনের সাথে জটিলতা",),
    "and heart problems": ("এবং হৃদরোগে",),
    "and immune system disorders": ("এবং ইমিউন সিস্টেমের",),
    "and muscles": ("এবং পেশী",),
    "and some types of high blood pressure": ("এবং কিছু ধরনের উচ্চ রক্তচাপ",),
    "and watery eyes are allergies": ("এবং জলের চোখ অ্যালার্জি",),
    "and zollinger-ellison syndrome": ("এবং জোলিঙ্গার-এলিসন সিন্ড্রোম",),
    "androgen glands": ("অ্যান্ড্রোজেন গ্রন্থি",),
    "anemia": ("অ্যানিমিয়া", "অ্যানিমিয়া",),
    "anesthetic": ("অ্যানেস্থেটিক",),
    "angina": ("অ্যানজাইনা", "এনজাইনা", "এনজিনা",),
    "angioedema": ("অ্যাঞ্জিওডিমা", "এনজিওএডিমা",),
    "angioplasty": ("এনজিওপ্লাস্টি",),
    "ankylosing spondylitis": ("এনকাইলজিং স্পন্ডিলাইটিস",),
    "ankylosis spondylitis": ("অ্যানকিলোসিস স্পন্ডিলাইটিস",),
    "anorexia": ("অ্যানোরেক্সিয়া",),
    "anorexia nervosa": ("অ্যানোরেক্সিয়া নার্ভোসা",),
    "anovulation": ("অ্যানোভুলেশন",),
    "antacid": ("অ্যান্টাসিড", "এন্টাসিড",),
    "antacids": ("অ্যান্টাসিড",),
    "anterior lobe": ("পূর্ববর্তী লোব",),
    "anthrax": ("অ্যানথ্রাক্স",),
    "anti-diabetic": ("অ্যান্টি-ডায়াবেটিক",),
    "anti-diabetic drugs": ("অ্যান্টি-ডায়াবেটিক ওষুধ",),
    "anti-diarrheal": ("অ্যান্টি-ডায়রিয়ারিক",),
    "anti-diuretic": ("অ্যান্টি-মূত্রবর্ধক",),
    "anti-inflammatory": ("অ্যান্টি-ইনফ্ল্যামেটরি",),
    "anti-inflammatory pain": ("অ্যান্টি-ইনফ্যামম্যাটারী ব্যথা",),
    "antiandrogenic": ("অ্যান্টিঅ্যান্ড্রোজেনিক", "এন্টিঅ্যান্ড্রোজেনিক",),
    "antibiotics": ("অ্যান্টিবায়োটিক", "অ্যান্টিবায়োটিক", "অ্যাান্টিবায়োটিক",),
    "antibodies": ("অ্যান্টিবডি",),
    "antibody production": ("অ্যান্টিবডি তৈরি",),
    "anticancer drugs": ("অ্যান্টিক্যান্সার ওষুধ",),
    "anticoagulant": ("অ্যান্টিকোয়াগুলেন্ট", "এন্টিকোয়াগুলেন্ট",),
    "anticonvulsant": ("অ্যান্টিকনভালসেন্ট",),
    "antidepressant": ("অ্যান্টিডিপ্রেসেন্ট",),
    "antidepressants": ("এন্টিডিপ্রেসেন্ট",),
    "antidiuresis": ("অ্যান্টিডিউরিসিস", "অ্যান্টিডিউরেসিস",),
    "antidiuretic": ("অ্যান্টিডিউরেটিক",),
    "antidopaminergic": ("অ্যান্টিডোপামিনার্জিক",),
    "antihistamine": ("অ্যান্টিহিস্টামিন",),
    "antihistamines": ("অ্যান্টিহিস্টামাইনস",),
    "antihypertensive": ("অ্যান্টিহাইপারটেনসিভ",),
    "antihypertensive agents": ("অ্যান্টিহাইপারটেনসিভ এজেন্ট",),
    "antimineralocorticoids": ("অ্যান্টিমিনারলোকোর্টিকয়েড",),
    "antiprogestogenic": ("অ্যান্টিপ্রজেস্টোজেনিক",),
    "antipsychotic": ("অ্যান্টিসাইকোটিক",),
    "anuria": ("অ্যানুরিয়া",),
    "anus": ("মলদ্বার",),
    "anxiety": ("উদ্বিগ্নতা", "উদ্বেগ", "দুশ্চিন্তা",),
    "anxiety disorder": ("উদ্বেগজনক ব্যাধি", "উদ্বেগজনিত ব্যাধি",),
    "anxiety disorders": ("উদ্বেগ রোগ", "উদ্বেগজনিত ব্যাধি",),
    "aorta": ("মহাধমনী",),
    "aortic stenosis": ("মহাধমনী স্টেনোসিস",),
    "appetite suppression problems": ("ক্ষুধা দমন সংক্রান্ত সমস্যা",),
    "aquaporin": ("অ্যাকোয়াপোরিন",),
    "arginine vasopressin": ("আর্জিনাইন ভ্যাসোপ্রেসিন",),
    "arousal": ("উত্তেজনা",),
    "arrhythmia": ("অ্যারিথমিয়া", "এরিথমিয়া",),
    "arteries": ("ধমনী",),
    "arteriosclerosis": ("আর্টারিওসক্লেরোসিস",),
    "artery": ("ধমনী",),
    "arthritis": ("আথ্রাইটিস", "আর্থারিসিস", "আর্থ্রাইটিস", "আর্থ্রাইটিসের", "বাত",),
    "arthritis pain": ("বাতজনিত ব্যথা", "বাতের ব্যথা",),
    "artificial analogue": ("কৃত্রিম অ্যানালগ",),
    "artificial growth hormone": ("কৃত্রিম গ্রোথ হরমোন",),
    "ascending loop of henle": ("হেনলের আরোহী লুপ",),
    "ascites": ("অ্যাসাইটস",),
    "ascorbate": ("অ্যাসকরবেট",),
    "aseptic": ("অ্যাসেপটিক",),
    "asthenia": ("অ্যাসথেনিয়া",),
    "asthma": ("অ্যাজমা", "অ্যাস্থমা", "এজমা", "হাঁপানি",),
    "asthma and urticaria": ("হাঁপানি ও অর্টিকারিয়া",),
    "asthma control": ("হাঁপানি নিয়ন্ত্রণ",),
    "asymptomatic": ("উপসর্গহীন",),
    "asystole": ("অ্যাসিস্টোল",),
    "at bedtime": ("শোবার সময়",),
    "athlete": ("ক্রীড়াবিদ",),
    "athlete's foot": ("অ্যাথলিটের পা", "অ্যাথলেটস ফুট", "ক্রীড়াবিদের পা",),
    "athletes": ("এথলেট",),
    "athletic performance": ("অ্যাথলেটিক পারফরম্যান্স",),
    "atopic dermatitis": ("এটোপিক ডার্মাটাইটিস",),
    "atrial fibrillation": ("অ্যাট্রিয়াল ফাইব্রিলেশন", "এট্রিয়াল ফিব্রিলেশন",),
    "attention deficit disorder": ("মনোযোগের অভাবজনিত ব্যাধি",),
    "autism": ("অটিজম",),
    "autism spectrum disorder": ("অটিজম স্পেকট্রাম ডিসঅর্ডার",),
    "auto-immune": ("অটো-ইমিউন",),
    "autoimmune": ("অটোইমিউন",),
    "autoimmune diseases": ("অটোইমিউন রোগ",),
    "autoimmune disorders": ("অটোইমিউন ডিসঅর্ডার",),
    "autoimmune hepatitis": ("অটোইমিউন হেপাটাইটিস",),
    "autonomic neuropathy": ("স্বায়ত্তশাসিত নিউরোপ্যাথি",),
    "awareness of use": ("ব্যবহারের সচেতনতা",),
    "axon": ("অ্যাক্সন",),
    "b complex": ("বি কমপ্লেক্স",),
    "b vitamin deficiency": ("বি ভিটামিনের ঘাটতি",),
    "baby's hunger": ("শিশুর অনাহার",),
    "back": ("পিঠ",),
    "back pain": ("কোমর ব্যথা", "পিঠে ব্যথা", "পিঠে ব্যাথা",),
    "back pain or toothache": ("পিঠে ব্যথা বা দাঁতের ব্যথার",),
    "bacteria": ("ব্যাকটেরিয়া",),
    "bacterial cell wall": ("ব্যাকটেরিয়া কোষ প্রাচীর",),
    "bacterial dna": ("ব্যাকটেরিয়া ডিএনএ",),
    "bacterial infection": ("ব্যাকটেরিয়া ঘটিত সংক্রমণ", "ব্যাকটেরিয়া সংক্রমণ", "ব্যাকটেরিয়াজনিত সংক্রমণ", "ব্যাকটেরিয়াল সংক্রমণ",),
    "bacterial infections": ("ব্যাকটেরিয়া সংক্রমণ",),
    "bacterial meningitis": ("ব্যাকটেরিয়াজনিত মেনিনজাইটিস", "ব্যাকটেরিয়াল মেনিনজাইটিস",),
    "bacterial synthesis": ("ব্যাকটেরিয়া সংশ্লেষণ",),
    "bacterial vaginosis": ("ব্যাকটেরিয়া ভ্যাজিনোসিস", "ব্যাকটেরিয়াল  ভ্যাজিনোসিস",),
    "bactericidal": ("ব্যাকটেরিসাইডাল",),
    "bactericidal action": ("ব্যাকটেরিয়াঘটিত ক্রিয়া",),
    "bad taste": ("খারাপ স্বাদ",),
    "balance": ("ভারসাম্য",),
    "balanced diet": ("সুষম খাদ্য",),
    "barbarity": ("বর্বরতা",),
    "barter syndrome": ("বার্টারের সিন্ড্রোম",),
    "basal metabolic rate": ("মৌল বিপাকীয় হার",),
    "basic painkillers": ("বেসিক পেইন কিলার",),
    "bedwetting": ("বিছানা ভিজানো", "বিছানা ভেজানো",),
    "behavior control": ("আচরণ নিয়ন্ত্রণ",),
    "behavioral abnormalities": ("আচরণগত বৈপরীত্য",),
    "behavioral therapy": ("বিহেভিয়েরাল থেরাপি",),
    "benefits": ("সুবিধা",),
    "betamethasone": ("বিটামিথাসন",),
    "binding": ("আবদ্ধ করা", "বাইন্ডিং",),
    "bipolar disorder": ("বাইপোলার ডিসঅর্ডার",),
    "birth defects": ("জন্মগত ত্রুটি",),
    "bite swelling": ("কামড় ফোলা",),
    "black market": ("কালোবাজার",),
    "bladder": ("মূত্রথলি", "মূত্রাশয়",),
    "bladder cancer": ("মূত্রথলির ক্যান্সার",),
    "bladder infection": ("মূত্রথলিতে ইনফেকশন",),
    "bladder spasm": ("মূত্রাশয় খিঁচুনি",),
    "bleeding": ("রক্তক্ষরণ", "রক্তপাত",),
    "bleeding abnormalities": ("রক্তপাতের অস্বাভাবিকতা",),
    "bleeding and mortality rates": ("রক্তপাত এবং মৃত্যুর হার",),
    "bleeding control": ("রক্তপাত নিয়ন্ত্রণ",),
    "bleeding disorders": ("রক্তপাতের ব্যাধি",),
    "blindness": ("অন্ধত্ব",),
    "blister": ("ফসকা",),
    "blister packing": ("ফোস্কা প্যাকিং",),
    "blistering": ("ফোসকা পড়া",),
    "blisters": ("ফোসকা", "ফোস্কা",),
    "bloating": ("ব্লোটিং",),
    "block": ("ব্লক",),
    "blockage in blood vessels": ("রক্তনালীতে ব্লকেজ",),
    "blocks the proton pump in stomach cells": ("পেটের কোষে প্রোটন পাম্পকে ব্লক",),
    "blood": ("রক্ত",),
    "blood analysis": ("রক্ত বিশ্লেষণ",),
    "blood and cells": ("রক্ত এবং কোষ",),
    "blood circulation": ("রক্ত সঞ্চালন",),
    "blood clot": ("রক্ত জমাট", "রক্ত জমাট বাঁধা",),
    "blood clots": ("ক্ত জমাট বাঁধা", "রক্ত জমাট",),
    "blood clotting": ("রক্ত জমাট বাঁধা",),
    "blood clotting disorders": ("রক্ত জমাট বাঁধার ব্যাধি",),
    "blood flow": ("রক্ত প্রবাহ", "রক্ত ​​প্রবাহ", "রক্তপ্রবাহ",),
    "blood ion balance": ("রক্তে আয়নের ভারসাম্য",),
    "blood pressure": ("ব্লাডপ্রেশার", "রক্তচাপ",),
    "blood pump": ("রক্ত পাম্প",),
    "blood salts": ("রক্তের লবণ",),
    "blood secretion": ("রক্তে নির্গমন।",),
    "blood sodium levels": ("রক্তে সোডিয়ামের পরিমাণ",),
    "blood sugar": ("রক্তে শর্করার",),
    "blood supply": ("রক্ত সরবরাহ",),
    "blood test": ("রক্ত ​​পরীক্ষা",),
    "blood vessel": ("রক্তনালী", "রক্তবাহিকা",),
    "blood vessel relaxation": ("রক্তনালীর শিথিলতা",),
    "blood vessels": ("রক্তনালি", "রক্তনালিকা", "রক্তনালী", "রক্তবাহী নালী", "রক্তবাহী পাত্র",),
    "blood vessels and arteries": ("রক্তনালী এবং ধমনী",),
    "blood vessels and kidneys": ("রক্তবাহী নালী এবং কিডনি",),
    "blood volume": ("রক্তের পরিমাণ",),
    "blood/hormone problems": ("রক্ত/হরমোনের সমস্যা",),
    "bloodstream": ("রক্তপ্রবাহ",),
    "blurred vision": ("ঝাপসা দৃষ্টি",),
    "body": ("শরীর",),
    "body ache": ("শরীরে ব্যথা",),
    "body aches": ("শরীরে ব্যথা",),
    "body cells": ("দেহকোষ",),
    "body coordination": ("শরীরের সমন্বয়",),
    "bodybuilders": ("বডিবিল্ডার।",),
    "bonding": ("বন্ধন",),
    "bone": ("হাড়", "হাড়",),
    "bone density": ("হাড়ের ঘনত্ব",),
    "bone destruction": ("হাড়ের ধ্বংস",),
    "bone disease": ("হাড়ের রোগ",),
    "bone growth": ("হাড় বৃদ্ধি", "হাড়ের বৃদ্ধি।",),
    "bone health problems": ("হাড়ের স্বাস্থ্য সমস্যা",),
    "bone loss": ("হাড় ক্ষয়", "হাড়ের ক্ষয়",),
    "bone mass": ("হাড়ের ভর",),
    "bone metastases": ("হাড়ের মেটাস্টেস",),
    "bone remodeling": ("হাড়ের পুনর্নির্মাণ",),
    "bone structure": ("হাড়ের গঠন",),
    "bone tissue": ("হাড়ের টিস্যু",),
    "bones": ("হাড়",),
    "bones and muscles": ("হাড় ও পেশী",),
    "book": ("বুক",),
    "bradycardia": ("ব্র্যাডিকার্ডিয়া",),
    "brain": ("ব্রেন", "মস্তিষ্ক", "মস্তিষ্ক্‌",),
    "brain and gut": ("মস্তিষ্ক এবং অন্ত্র",),
    "brain and nervous system": ("মস্তিষ্ক এবং স্নায়ুতন্ত্র।",),
    "brain hemorrhage": ("মস্তিষ্কে রক্তক্ষরণ",),
    "brain tumors": ("ব্রেন টিউমার", "মস্তিষ্কের টিউমার",),
    "brainstem": ("ব্রেনস্টেম",),
    "brand name": ("ব্র্যান্ড নাম",),
    "breakdown of bone matrix": ("হাড়ের ম্যাট্রিক্সের ভাঙ্গন",),
    "breakdown of bone tissue": ("হাড়ের টিস্যু ভাঙ্গার",),
    "breakthrough bleeding": ("যুগান্তকারী রক্তপাত",),
    "breast": ("বুক", "স্তন", "স্তন্য", "স্তন্যগ্রন্থি",),
    "breast cancer": ("স্তন ক্যান্সার",),
    "breast milk": ("বুকের দুধ", "মাতৃদুগ্ধ",),
    "breast tissue": ("স্তনের টিস্যুর",),
    "breast tumors": ("স্তনের টিউমার",),
    "breastfeeding": ("বুকের দুধ", "বুকের দুধ খাওয়ানো", "মাতৃদুগ্ধ", "স্তন্যপান",),
    "breasts": ("স্তন",),
    "breathing": ("শ্বাস প্রশ্বাস",),
    "breathing difficulties": ("শ্বাসকষ্ট",),
    "breathing problems": ("শ্বাসকষ্ট", "শ্বাসপ্রশ্বাসের সমস্যা",),
    "broad-spectrum": ("ব্রড-স্পেকট্রাম",),
    "bronchi": ("ব্রঙ্কি",),
    "bronchial": ("শ্বাসনালী", "শ্বাসনালীর",),
    "bronchial asthma": ("ব্রঙ্কিয়াল হাঁপানি",),
    "bronchitis": ("ব্রংকাইটিস", "ব্রঙ্কাইটিস",),
    "bronchoconstriction": ("ব্রঙ্কোকনস্ট্রিকশন",),
    "bronchodilator": ("ব্রঙ্কোডাইলেটর",),
    "bronchodilatory effect": ("ব্রঙ্কোডাইলেটরি প্রভাব",),
    "bronchoscopy": ("ব্রঙ্কোস্কোপি",),
    "bronchospasm": ("ব্রঙ্কসপাসম", "ব্রঙ্কোস্পাজম",),
    "bruising": ("চূর্ণ",),
    "bruxism": ("ব্রুক্সিজম",),
    "bulimia": ("বুলিমিয়া",),
    "bulimia nervosa": ("বুলিমিয়া নার্ভোসা",),
    "burning": ("জ্বলন্ত",),
    "burning mouth syndrome": ("বার্নিং মাউথ সিনড্রোম",),
    "burns": ("পোড়া",),
    "buscopan": ("বুস্কোপ্যান",),
    "butamirate": ("বুটামিরেট",),
    "c-cell hyperplasia": ("সি-সেল হাইপারপ্লাসিয়া",),
    "calcitonin": ("ক্যালসিটোনিন",),
    "calming effect": ("শান্ত প্রভাব",),
    "calming effects": ("প্রশান্তিদায়ক প্রভাব",),
    "cancer": ("ক্যান্সার",),
    "candidiasis": ("ক্যান্ডিডিয়াসিস",),
    "candidiasis of the oral cavity": ("মুখগহ্বরের ক্যান্ডিডিয়াসিস",),
    "canker sores": ("ক্যানকার কালশিটে",),
    "capacity": ("ক্ষমতা",),
    "capillaries": ("কৈশিক", "কৈশিক নালী",),
    "capsule": ("ক্যাপসুল",),
    "capsule or tablet": ("ক্যাপসুল বা ট্যাবলেট",),
    "capsules": ("ক্যাপসুল",),
    "capsules and suppositories": ("ক্যাপসুল এবং সাপোজিটরি",),
    "cardiac": ("কার্ডিয়াক",),
    "cardiac arrest": ("কার্ডিয়াক অ্যারেস্ট", "কার্ডিয়াক অ্যারেস্টে",),
    "cardiac arrhythmia": ("কার্ডিয়াক অ্যারিথমিয়া",),
    "cardiac insufficiency": ("কার্ডিয়াক অপ্রতুলতা",),
    "cardiac output": ("কার্ডিয়াক আউটপুট",),
    "cardiac tamponade": ("কার্ডিয়াক ট্যাম্পোনেড",),
    "cardio-respiratory": ("কার্ডিও-রেসপিরেটরি",),
    "cardio-respiratory therapy": ("কার্ডিও-রেসপিরেটরি চিকিৎসা",),
    "cardiogenic": ("কার্ডিওজেনিক",),
    "cardiogenic shock": ("কার্ডিওজেনিক শক",),
    "cardiomyocyte": ("কার্ডিওমায়োসাইট",),
    "cardiomyocytes": ("কার্ডিওমায়োসাইট",),
    "cardiopulmonary arrest": ("কার্ডিওপালমোনারি অ্যারেস্ট",),
    "cardiovascular": ("কার্ডিওভাসকুলার",),
    "cardiovascular disease": ("কার্ডিওভাসকুলার ডিজিজ", "কার্ডিওভাসকুলার রোগ",),
    "cardiovascular events": ("কার্ডিওভাসকুলার ইভেন্ট",),
    "cardiovascular risk": ("কার্ডিওভাসকুলার ঝুঁকি",),
    "cardiovascular system": ("কার্ডিওভাসকুলার সিস্টেম", "হৃদপিণ্ড",),
    "care": ("যত্ন",),
    "carotid sinus": ("ক্যারোটিড সাইনাস",),
    "carrier proteins": ("ক্যারিয়ার প্রোটিন",),
    "cartilage": ("তরুণাস্থি",),
    "cascade": ("ক্যাসকেড",),
    "catalyzed": ("অনুঘটকিত",),
    "cataract": ("ছানি",),
    "cataracts": ("ছানি",),
    "catecholamine resistant shock": ("ক্যাটেকোলামাইন প্রতিরোধী শক",),
    "catecholamines": ("ক্যাটেকোলামাইন",),
    "cattle body cells": ("গবাদি পশুর দেহের কোষ",),
    "caution": ("সতর্কতা",),
    "ceftin": ("সেফটিন",),
    "cefzil": ("সেফজিল",),
    "cell": ("কোষ",),
    "cell membrane": ("কোষের ঝিল্লি",),
    "cell regeneration": ("কোষ পুনর্জন্ম।",),
    "cell reproduction": ("কোষ প্রজনন",),
    "cell surface": ("কোষের পৃষ্ঠ",),
    "cells": ("কোষ",),
    "cellulitis": ("সেলুলাইটিস",),
    "central diabetes insipidus": ("সেন্ট্রাল ডায়াবেটিস ইনসিপিডাস",),
    "central effect": ("কেন্দ্রীয় প্রভাব",),
    "central influence": ("কেন্দ্রীয় প্রভাব",),
    "central nervous system": ("কেন্দ্রীয় স্নায়ুতন্ত্র", "সেন্ট্রাল নার্ভাস সিস্টেম", "সেন্ট্রাল স্নায়ুতন্ত্র",),
    "cerebellum": ("সেরিবেলাম",),
    "cerebral arteries": ("সেরিব্রাল ধমনী",),
    "cerebral edema": ("সেরিব্রাল এডমা", "সেরিব্রাল শোথ",),
    "certain intestinal diseases": ("নির্দিষ্ট অন্ত্রের রোগ",),
    "cervical cancer": ("জরায়ু ক্যান্সার",),
    "cervical dilatation": ("সারভিক্সের প্রশারতা",),
    "cervix uteri": ("সারভিক্স ইউটেরি",),
    "changes in efficacy": ("কার্যকারিতা পরিবর্তন",),
    "chemical": ("রাসায়নিক",),
    "chemical substances": ("রাসায়নিক পদার্থ",),
    "chemo": ("কেমো",),
    "chemotherapy": ("কেমোথেরাপি",),
    "chemotherapy and radiotherapy": ("কেমোথেরাপি এবং রেডিওথেরাপি",),
    "chest": ("বক্ষ", "বুক",),
    "chest and throat infections": ("বুকে এবং গলা সংক্রমণ",),
    "chest infection": ("বুকের সংক্রমণ",),
    "chest infections": ("বুকে সংক্রমণ",),
    "chest pain": ("বুকে ব্যথা",),
    "chest tightness": ("বুকের দম বন্ধ হওয়া",),
    "chickenpox": ("চিকেনপক্স",),
    "childbirth": ("প্রসব", "সন্তান প্রসব",),
    "children": ("শিশু",),
    "chills": ("ঠান্ডা লাগা",),
    "cholesterol": ("কলেস্টেরলের", "কোলেস্টেরল",),
    "cholesterol and triglycerides": ("কলেস্টেরল এবং ট্রাইগ্লিসারাইড",),
    "cholesterol related problems": ("কোলেস্টেরল সম্পর্কিত সমস্যা",),
    "chromaffin cells": ("ক্রোমাফিন কোষ",),
    "chromosomes": ("ক্রোমোজোম",),
    "chronic bronchitis": ("দীর্ঘস্থায়ী ব্রঙ্কাইটিস",),
    "chronic inflammation": ("দীর্ঘস্থায়ী প্রদাহ",),
    "chronic renal failure": ("দীর্ঘস্থায়ী কিডনি ব্যর্থতা",),
    "chronic stress": ("দীর্ঘস্থায়ী চাপ",),
    "chronic systemic conditions": ("দীর্ঘস্থায়ী পদ্ধতিগত অবস্থা",),
    "churg-strauss syndrome": ("চুর্গ-স্ট্রস সিনড্রোম",),
    "circadian rhythm": ("সার্কাডিয়ান ছন্দ", "সার্কাডিয়ান রিদম",),
    "circadian rhythms": ("সার্কাডিয়ান ছন্দ",),
    "circulation": ("সঞ্চালন",),
    "cirrhosis": ("সিরোসিস",),
    "clarithromycin": ("ক্ল্যারিথ্রোমাইসিন",),
    "class c": ("ক্লাস সি",),
    "clinical": ("ক্লিনিকাল", "ক্লিনিক্যাল",),
    "clinical problems": ("ক্লিনিকাল সমস্যা।",),
    "clinical trials": ("ক্লিনিকাল ট্রায়াল",),
    "clinically": ("ক্লিনিক্যালি",),
    "clot": ("ক্লট",),
    "clotting or bleeding problems": ("জমাট বাঁধা বা রক্তপাতের সমস্যা",),
    "coagulation test": ("কোয়াগুলেশন টেস্ট",),
    "codeine": ("কোডাইন",),
    "cofactor": ("কোফ্যাক্টর",),
    "cofactors": ("কোফ্যাক্টর",),
    "cold": ("সর্দি",),
    "colds": ("সর্দি",),
    "colitis": ("কোলাইটিস",),
    "collagen": ("কোলাজেন",),
    "collecting duct": ("সংগ্রাহী ডাক্ট",),
    "collecting ducts": ("সংগ্রহকারী নালী",),
    "colon": ("কোলন",),
    "coma": ("কোমা",),
    "common cold": ("সাধারণ ঠান্ডা", "সাধারণ সর্দি",),
    "competing products": ("প্রতিযোগী পণ্য",),
    "complications": ("কম্বোডি হ্রাস",),
    "complications during childbirth": ("প্রসবকালীন জটিলতা",),
    "complications during pregnancy": ("গর্ভাবস্থায় জটিলতা",),
    "concerns": ("উদ্বেগ",),
    "concomitant use": ("একযোগে ব্যবহার",),
    "conditions": ("অবস্থার",),
    "conflict": ("দ্বন্দ্ব",),
    "confusion": ("ঝাপসা ভাব",),
    "congenital": ("জন্মগত",),
    "congenital growth deficiency": ("জন্মগত বৃদ্ধি ঘাটতি",),
    "congestive heart failure": ("কনজেস্টিভ হার্ট ফেইল", "কনজেস্টিভ হার্ট ফেইলিউর",),
    "conjunctivitis": ("কনজেক্টিভাইটিস",),
    "conn's syndrome": ("কন'স সিনড্রোম", "কনস সিনড্রোম",),
    "connecting tubules": ("সংযোগকারী টিউবিল",),
    "constipation": ("কোষ্ট কাঠিন্য", "কোষ্ঠকাঠিন্য",),
    "contact dermatitis": ("যোগাযোগ ডার্মাটাইটিস",),
    "contraindications": ("প্রতিনির্দেশনা",),
    "control": ("নিয়ন্ত্রণ",),
    "control test": ("কন্ট্রোল টেস্ট",),
    "controlled drugs": ("নিয়ন্ত্রিত ওষুধ",),
    "controlled substances": ("নিয়ন্ত্রিত পদার্থ",),
    "convulsions": ("খিঁচুনি", "খিঁচুনী",),
    "copd": ("সিওপিডি",),
    "coronary": ("করোনারি",),
    "coronary artery": ("করনরি আর্টারি",),
    "coronary heart disease": ("করোনারি হৃদরোগ",),
    "corpus luteum": ("কর্পাস লুটিয়াম",),
    "cortical neurons": ("কর্টিকাল নিউরন",),
    "corticosteroids": ("কর্টিকোস্টেরয়েড",),
    "cough": ("কাশি",),
    "cough center": ("কাশি কেন্দ্র",),
    "cough center in the brain": ("মস্তিষ্কের কাশি কেন্দ্র",),
    "cough medicine": ("কাশির ওষুধ",),
    "cough reflex": ("কফ রিফ্লেক্স", "কাশি প্রতিফলন",),
    "cough relief": ("কাশি উপশম",),
    "cough suppressant": ("কাশি দমন", "কাশি দমনকারী",),
    "cough suppression": ("কাশি দমন",),
    "course": ("কোর্স",),
    "cpr": ("সিপিআর",),
    "cramping": ("ক্র্যাম্পিং",),
    "cramps": ("খিঁচুনি",),
    "cream": ("ক্রিম",),
    "cream doctor": ("ক্রিম ডাক্তারের",),
    "creams": ("ক্রিম",),
    "crohn's disease": ("ক্রোনস ডিজিজ", "ক্রোনের রোগ",),
    "crusting": ("ক্রাস্টিং",),
    "crystalluria": ("ক্রিষ্টালইউরিয়া",),
    "crystalluria and the kidneys": ("ক্রিস্টালুরিয়া এবং কিডনির",),
    "cushing": ("কুশিং",),
    "cushing's disease": ("কুশিং ডিজিজ",),
    "cushing's syndrome": ("কুশিং সিন্ড্রোম",),
    "cuts": ("কাটা",),
    "cyclooxygenase": ("সাইক্লোকক্সিজেনেশ", "সাইক্লোকোক্সিজেন",),
    "cytoplasmic space": ("সাইটোপ্লাজমিক স্পেস",),
    "damage to the hypothalamus": ("হাইপোথ্যালামাস",),
    "dark urine": ("অন্ধকার মূত্র", "গাঢ় প্রস্রাব",),
    "de-iodination": ("ডি-আয়োডিনেশন",),
    "death": ("মৃত্যু",),
    "deconvolution": ("ডিকনভোলিউশন",),
    "decreased activity": ("কার্যকলাপ হ্রাস",),
    "decreased blood flow to the kidneys": ("কিডনিতে রক্ত প্রবাহ কমে যাওয়া",),
    "decreased bone density": ("হাড়ের ঘনত্ব কমে যাওয়া", "হাড়ের ঘনত্ব হ্রাস।",),
    "decreased libido": ("লিবিডো কমে যাওয়া", "লিবিডো হ্রাস",),
    "decreased muscle mass": ("পেশী ভর হ্রাস",),
    "decreased systolic blood pressure": ("সিস্টোলিক রক্তচাপ হ্রাস",),
    "decreased testicular size": ("টেস্টিকুলার আকার হ্রাস",),
    "deep sleep": ("গভীর ঘুম",),
    "deficiency": ("অভাব", "ঘাটতি",),
    "dehydrated": ("ডিহাইড্রেটেড",),
    "dehydration": ("ডিহাইড্রেশন", "পানিশূন্যতা",),
    "dementia": ("ডিমেনশিয়া",),
    "dengue": ("ডেঙ্গু",),
    "density gradient": ("ঘনত্বের গ্রেডিয়েন্ট",),
    "density storage": ("ঘনত্ব সঞ্চয়",),
    "dental infections": ("দাঁতের সংক্রমণ",),
    "dentist": ("ডেন্টিস্ট",),
    "dependence": ("নির্ভরতা",),
    "depressed": ("ডিপ্রেসেড",),
    "depressed mood": ("বিষণ্ণ মেজাজ",),
    "depression": ("ডিপ্রেশন", "বিষণ্ণতা", "বিষণ্নতা", "বিষন্নতা", "হতাশা",),
    "dermatitis": ("চর্মরোগ", "ডার্মাটাইটিস",),
    "dermatophytosis": ("ডার্মাটোফাইটোসিস",),
    "designer steroids": ("ডিজাইনার স্টেরয়েড",),
    "determined": ("নির্ধারিত",),
    "dexamethasone": ("ডেক্সামিথাসোন",),
    "diabetes": ("ডায়াবেটিস", "ডায়াবেটিসের", "ডায়েবেটিস", "ডায়াবেটিস", "মধুমেহ বা ডায়াবেটিস",),
    "diabetes insipidus": ("ডায়াবেটিস ইনসিপিডাস",),
    "diabetes mellitus": ("ডায়াবেটিস মেলাইটাস", "ডায়াবেটিস মেলিটাস",),
    "diabetic": ("ডায়াবেটিক", "ডায়াবেটিক",),
    "diabetic coma": ("ডায়াবেটিক কোমা",),
    "diabetic ketoacidosis": ("ডায়াবেটিক কেটোঅ্যাসিডোসিস",),
    "diabetic kidney disease": ("ডায়াবেটিক কিডনি রোগ",),
    "diabetic nephropathy": ("ডায়াবেটিক নেফ্রোপ্যাথি",),
    "diabetic retinopathy": ("ডায়াবেটিক রেটিনোপ্যাথি",),
    "dialysis": ("ডায়ালাইসিস", "ডায়ালাইসিস",),
    "diaper rash": ("ডায়াপার ফুসকুড়ি",),
    "diaphragm": ("ডায়াফ্রাম",),
    "diarrhea": ("অতিসার", "ডায়রিয়া", "ডায়রিয়া",),
    "diarrhea or constipation": ("ডায়রিয়া বা কোষ্ঠকাঠিন্য",),
    "diarrhea or intestinal complications": ("ডায়রিয়া বা অন্ত্রের জটিলতা",),
    "diastolic pressure": ("ডায়াস্টোলিক চাপ",),
    "diet": ("ডায়েট",),
    "diethylaminoethoxyethanol": ("ডাইথাইলামিনোইথোক্সিথানল",),
    "differentiation": ("পার্থক্য",),
    "difficulty breathing": ("শ্বাস নিতে সমস্যা",),
    "digestive problems": ("হজম সংক্রান্ত সমস্যা", "হজমজনিত সমস্যা", "হজমের সমস্যা",),
    "digestive system": ("পরিপাক তন্ত্র", "পরিপাকতন্ত্র", "পাচনতন্ত্র", "পৌস্টিক তন্ত্র",),
    "digestive tract": ("পরিপাক নালী",),
    "digoxin": ("ডিগক্সিন",),
    "dimpling": ("ডিম্পলিং",),
    "direct action": ("সরাসরি কাজ",),
    "directions": ("দিকনির্দেশ",),
    "discharge": ("নিঃসরণ", "স্রাব",),
    "discomfort": ("অস্বস্তি",),
    "discomfort in the limbs": ("অঙ্গপ্রত্যঙ্গে অস্বস্তি",),
    "discontinuation": ("বন্ধ করা",),
    "discouraged": ("নিরুৎসাহিত",),
    "disease prevention": ("রোগপ্রতিরোধ",),
    "disorder": ("ডিসঅর্ডার", "ব্যাধি",),
    "disordered eating": ("দ্বিধাহীন খাওয়া",),
    "disorders": ("ব্যাধি",),
    "diuretic": ("মূত্রবর্ধক",),
    "dizziness": ("মাথা ঘোরা",),
    "dna": ("ডিএনএ",),
    "doctor": ("চিকিৎসক", "ডাক্তার",),
    "doctor or pharmacist": ("ডাক্তার বা ফার্মাসিস্টের",),
    "doctor's": ("ডাক্তারের",),
    "doctor's advice": ("চিকিৎসকের পরামর্শ", "ডাক্তারের পরামর্শ",),
    "doctor's order": ("ডাক্তারের আদেশ",),
    "doctors": ("ডাক্তার", "ডাক্তাররা",),
    "dopamine": ("ডোপামিন",),
    "dopamine production": ("ডোপামিন উৎপাদন",),
    "dopamine release": ("ডোপামিন নিঃসরণ",),
    "dopamine supplements": ("ডোপামিন সাপ্লিমেন্ট",),
    "doping": ("ডোপিং",),
    "dosage": ("ডোজ", "ডোজ বা মাত্রা", "ডোজে",),
    "dosage adjustment": ("ডোজ সামঞ্জস্য",),
    "dose": ("ডোজ",),
    "dose reduction": ("ডোজ হ্রাস",),
    "dose-dependent": ("ডোজ-নির্ভর",),
    "doses": ("ডোজ",),
    "double dose": ("ডবল ডোজ",),
    "dress syndrome": ("ড্রেস সিন্ড্রোম",),
    "drop in hematocrit": ("হিমাটোক্রিট-এর পতন",),
    "drowsiness": ("ঘুম ঘুম ভাব", "তন্দ্রা",),
    "drug": ("ওষুধ", "ড্রাগ",),
    "drug abuse": ("ড্রাগ অপব্যবহার",),
    "drug addiction": ("মাদকাসক্তি",),
    "drug dependence": ("মাদক নির্ভরতা",),
    "drug dosage": ("ওষুধ ডোজ",),
    "drug hypersensitivity": ("ওষুধের প্রতি সংবেদনশীলতা",),
    "drug interactions": ("ওষুধের মিথস্ক্রিয়া",),
    "drugs": ("ড্রাগ", "ড্রাগস",),
    "dry cough": ("শুকনো কাশি", "শুষ্ক কফ", "শুষ্ক কাশি",),
    "dry mouth": ("শুষ্ক মুখ",),
    "dryness": ("শুষ্কতা",),
    "duct cells": ("নালী কোষ",),
    "duodenum": ("ডিওডেনাম", "ডুওডেনাম",),
    "duodenumkidney": ("ডুওডেনামকিডনি",),
    "duration": ("সময়কাল",),
    "duration of action": ("কর্মের সময়কাল",),
    "dysentery": ("আমাশয়",),
    "dysfunction": ("ডিসফাংশন",),
    "dyslipidemia": ("ডিসলিপিডেমিয়া",),
    "dysmenorrhea": ("ডিসমেনােরিয়া",),
    "dyspepsia": ("ডিসপেপসিয়া",),
    "ear": ("কান",),
    "ear discharge": ("কানের স্রাব",),
    "ear infection": ("কান সংক্রমণ", "কানে সংক্রমণ", "কানের সংক্রমণ",),
    "ear infections": ("কানের  সংক্রমণ", "কানের ইনফেকশন", "কানের সংক্রমণ",),
    "ears": ("কান",),
    "ectopic production": ("একটোপিক উত্পাদন",),
    "eczema": ("একজিমা", "চর্বি",),
    "edema (swelling) and redness": ("শোথ (ফোলা) এবং লালভাব",),
    "effect": ("প্রভাব",),
    "effective": ("কার্যকর",),
    "efficacy": ("কার্যকারিতা",),
    "efficiency": ("দক্ষতা",),
    "ejaculation": ("বীর্য নির্গমন", "বীর্যপাত",),
    "ejaculation and sperm": ("বীর্যপাত এবং শুক্রাণু",),
    "ejection": ("ইজেকশন",),
    "electrolyte": ("ইলেক্ট্রলাইট", "ইলেক্ট্রোলাইট",),
    "electrolyte disorders": ("ইলেক্ট্রোলাইট ব্যাধি",),
    "elimination": ("নির্মূল",),
    "embolism": ("এম্বোলিজম",),
    "embryo": ("ভ্রূণ",),
    "emission": ("নিঃসরণ",),
    "empathy": ("সহানুভূতি",),
    "emphysema": ("এমফিসেমা",),
    "endocrine gland": ("অন্তঃস্রাবী গ্রন্থি",),
    "endocrine glands": ("অন্তঃস্রাবী গ্রন্থি",),
    "endocrinologist": ("এন্ডোক্রিনোলজিস্টের",),
    "endogenous peptides": ("অন্তঃসত্ত্বা পেপটাইড",),
    "endometrial cancer": ("এন্ডোমেট্রিয়ামের ক্যান্সার",),
    "endometrium": ("এন্ডোমেট্রিয়াম",),
    "endothelial cells": ("এন্ডোথেলিয়াল কোষ",),
    "energy supply": ("শক্তির সরবরাহ",),
    "enlarged prostate": ("বর্ধিত প্রস্টেট", "বিবর্ধিত প্রোস্টেট",),
    "enteric nervous system": ("এন্টেরিক নার্ভাস সিস্টেম",),
    "enterochromaffin cells": ("এন্টেরোক্রমাফিন কোষ",),
    "eosinophilic esophagitis": ("ইওসিনোফিলিক এসোফ্যাগাইটিস",),
    "epidermal necrolysis": ("এপিডার্মাল নেক্রোলাইসিস",),
    "epididymis": ("এপিডিডাইমিস",),
    "epilepsy": ("এপিলেপসি", "মৃগীরোগ",),
    "epinephrine": ("এপিনেফ্রিন",),
    "erectile dysfunction": ("ইরেক্টাইল ডিসফাংশন",),
    "erosive esophagitis": ("ইরোসিভ এসোফ্যাগাইটিস",),
    "esophageal": ("খাদ্যনালীর",),
    "esophageal cancer": ("খাদ্যনালী ক্যান্সার",),
    "esophageal spasm": ("অন্ননালী খিঁচুনি",),
    "esophageal variceal hemorrhage": ("খাদ্যনালীতে ভেরিসিয়াল হেমোরেজ", "খাদ্যনালীর ভেরিসিয়াল হেমোরেজ",),
    "esophagus": ("অন্ননালী", "খাদ্যনালী",),
    "esther": ("এস্টার",),
    "estrogen": ("ইস্ট্রোজেন",),
    "estrogen deficiency": ("ইস্ট্রোজেন ঘাটতি",),
    "estrogen therapy": ("ইস্ট্রোজেন থেরাপি", "এস্ট্রোজেন থেরাপি",),
    "etiology": ("ইটিওলজি",),
    "excess skin growth": ("অতিরিক্ত ত্বক বৃদ্ধি।",),
    "excessive drowsiness": ("অতিরিক্ত তন্দ্রা",),
    "excessive secretion": ("অতিরিক্ত নিঃসরণ",),
    "excretion": ("নির্গমন", "রেচন",),
    "exercise": ("ব্যায়াম",),
    "exercise-induced asthma": ("ব্যায়াম-প্ররোচিত হাঁপানি",),
    "expansion": ("প্রসারণ",),
    "expectorant": ("এক্সপেকটোরেন্ট", "কফের ওষুধ",),
    "expired": ("মেয়াদউত্তীর্ণ",),
    "expression": ("অভিব্যক্তি",),
    "external genitalia": ("বাহ্যিক যৌনাঙ্গ",),
    "eye diseases": ("চোখের রোগ",),
    "eye drops": ("চোখের ড্রপ",),
    "eye infection": ("চোখের সংক্রমণের",),
    "eye inflammation": ("চোখের প্রদাহ",),
    "eyes": ("চোখ",),
    "eyes nose": ("চোখ নাক",),
    "face": ("মুখ",),
    "facial discomfort": ("মুখের অস্বস্তি",),
    "falling asleep quickly": ("দ্রুত ঘুমিয়ে পড়া",),
    "fast heart rate": ("দ্রুত হার্ট রেট",),
    "fat breakdown": ("ফ্যাট ভাঙন।",),
    "fat distribution": ("চর্বি বিতরণ",),
    "fat tissue": ("চর্বি কলা",),
    "fat-soluble": ("চর্বি-দ্রবণীয়",),
    "fatal risk": ("মারাত্মক ঝুঁকি",),
    "fatigue": ("অবসাদ", "ক্লান্তি",),
    "female reproductive health": ("মহিলা প্রজনন স্বাস্থ্য",),
    "fertility": ("উর্বরতা",),
    "fertility problems": ("উর্বরতা সমস্যা",),
    "fertilized egg": ("নিষিক্ত ডিম্বাণু",),
    "fetal bradycardia": ("ভ্রূণের ব্রাডিকার্ডিয়া",),
    "fetal brain": ("ভ্রূণের মস্তিষ্ক",),
    "fetal development": ("ভ্রূণের বিকাশ",),
    "fetal expulsion": ("ভ্রূণ বহিষ্কার",),
    "fetal heart rate": ("ভ্রূণের হার্টরেট",),
    "fever": ("জ্বর",),
    "fibroblasts": ("ফাইব্রোব্লাস্ট",),
    "fibromyalgia": ("ফাইব্রোমায়ালজিয়া",),
    "filtration": ("পরিস্রাবণ",),
    "fingers": ("আঙ্গুল",),
    "first trimester": ("প্রথম ত্রৈমাসিকের",),
    "flatulence": ("পেট ফাঁপা", "ফ্ল্যাটুল",),
    "flatulence and dry mouth may occur": ("ফ্ল্যাটুলেন্স এবং শুকনো মুখ",),
    "flu": ("ফ্লু",),
    "fluid retention": ("তরল ধারণ",),
    "foam": ("ফোম",),
    "focused radiation": ("ফোকাসড রেডিয়েশন",),
    "folliculitis": ("ফলিকুলাইটিস",),
    "food": ("খাদ্য",),
    "food intake": ("খাদ্য গ্রহণ",),
    "food pipe": ("খাদ্যের নল",),
    "foot vagina": ("পা যোনি",),
    "for short-term use": ("স্বল্পমেয়াদী ব্যবহারের জন্য",),
    "forest": ("জঙ্গল",),
    "fracture": ("ফ্র্যাকচার", "ফ্র্যাকচারের",),
    "frequency": ("ফ্রিকোয়েন্সি",),
    "frequent waking": ("ঘন ঘন জেগে ওঠা",),
    "fruit juice": ("ফলের রস",),
    "function": ("ফাংশন",),
    "function test": ("ফাংশন পরীক্ষা",),
    "fundic gland": ("ফান্ডিক গ্রন্থি",),
    "fundic gland polyps": ("ফান্ডিক গ্রন্থি পলিপ",),
    "fungal": ("ছত্রাকজনিত",),
    "fungal infection": ("ছত্রাক সংক্রমণ", "ছত্রাকঘটিত সংক্রমণের",),
    "fungal infections": ("ছত্রাকের সংক্রমণ",),
    "g-protein-coupled": ("জি-প্রোটিন-সংযোজিত",),
    "galactorrhea": ("গ্যালাক্টোরিয়া",),
    "gallbladder": ("পিত্ত", "পিত্তথলি",),
    "gamete": ("গ্যামেট",),
    "gangrene": ("গ্যাংগ্রিন",),
    "gas": ("গ্যাস",),
    "gastric": ("গ্যাস্টিক", "গ্যাস্ট্রিক",),
    "gastric acid": ("গ্যাস্ট্রিক অ্যাসিড",),
    "gastric irritation": ("গ্যাস্ট্রিক জ্বালা",),
    "gastric parietal": ("গ্যাস্ট্রিক প্যারিটাল",),
    "gastric ulcer": ("গ্যাস্ট্রিক আলসার",),
    "gastritis": ("গ্যাস্ট্রাইটিস",),
    "gastroenterology": ("গ্যাস্ট্রোএন্টারোলজি",),
    "gastrointestinal": ("গ্যাস্ট্রোইনটেস্টাইনাল",),
    "gastrointestinal bleeding": ("গ্যাস্ট্রোইনটেস্টাইনাল রক্তপাত",),
    "gastrointestinal cramps": ("গ্যাস্ট্রোইনটেস্টাইনাল খিঁচুনি",),
    "gastrointestinal disorders": ("গ্যাস্ট্রোইনটেস্টাইনাল ব্যাধি",),
    "gastrointestinal infection": ("গ্যাস্ট্রোইনটেস্টাইনাল সংক্রমণ",),
    "gastrointestinal infections": ("গ্যাস্ট্রোইনটেস্টাইনাল সংক্রমণ",),
    "gastrointestinal system": ("গ্যাস্ট্রোইনটেস্টাইনাল সিস্টেম",),
    "gel": ("জেল",),
    "gelatin capsules": ("জেলটিন ক্যাপসুল",),
    "gels and ointments": ("জেল এবং মলম",),
    "gender dysphoria": ("লিঙ্গ ডিসফোরিয়া",),
    "gene": ("জিন",),
    "gene expression": ("জিনের অভিব্যক্তি",),
    "gene mutations": ("জিনের মিউটেশন",),
    "generosity": ("উদারতা",),
    "genetic conditions": ("জেনেটিক অবস্থা",),
    "genital tract": ("যৌনাঙ্গের ট্র্যাক্ট",),
    "genitals": ("যৌন অঙ্গ", "যৌনাঙ্গ",),
    "gerd": ("জিইআরডি",),
    "getting pregnant": ("গর্ভবতী হওয়া",),
    "giardiasis": ("গিয়ার্ডিয়াসিস",),
    "gland": ("গ্রন্থি",),
    "glaucoma": ("গ্লুকোমা",),
    "glossitis": ("গ্লোসাইটিস",),
    "glucose": ("গ্লুকোজ",),
    "glucose metabolism": ("গ্লুকোজ বিপাক",),
    "glucosuria": ("গ্লুকোসুরিয়া",),
    "glycemic": ("গ্লাইসেমিক",),
    "goiter": ("গলগণ্ড",),
    "gonad": ("গোনাড",),
    "gonadal hormones": ("গোনাডাল হরমোন",),
    "gonadotropic cells": ("গোনাডোট্রপিক কোষ",),
    "gonadotropin": ("গোনাডোট্রপিন", "গোনাডোট্রোপিন",),
    "gonads": ("গোনাড",),
    "gonorrhea": ("গণোরিয়া", "গনোরিয়া",),
    "gouty arthritis": ("গাউটি আর্থ্রাইটিস",),
    "government approval": ("সরকারি অনুমোদন।",),
    "gram-negative": ("গ্রাম-নেগেটিভ",),
    "gram-positive": ("গ্রাম-পজিটিভ",),
    "graves' disease": ("গ্রেভস রোগ",),
    "growth": ("বৃদ্ধি",),
    "growth deficiency": ("বৃদ্ধি ঘাটতি",),
    "growth deficit": ("বৃদ্ধি ঘাটতি",),
    "growth disorder": ("বৃদ্ধির ব্যাধি।",),
    "growth factor": ("গ্রোথ ফ্যাক্টর",),
    "growth hormone": ("গ্রোথ হরমোন",),
    "growth hormone deficiency": ("বৃদ্ধি হরমোনের ঘাটতি",),
    "growth of distal parts of the body": ("শরীরের দূরবর্তী অংশের বৃদ্ধি",),
    "growth-promoting activity": ("বৃদ্ধি-প্রচারকারী কার্যকলাপ।",),
    "gynecology": ("স্ত্রীরোগ",),
    "gynecomastia": ("গাইনেকোমাস্টিয়া", "গাইনোকোমাস্টিয়া",),
    "haemophilus influenzae": ("হেমােফিলাস ইনফ্লুয়েঞ্জা",),
    "hair": ("চুল",),
    "hair follicle": ("চুলের ফলিকল",),
    "hair follicles": ("চুলের ফলিকল",),
    "hair growth": ("চুলের বৃদ্ধি",),
    "hair loss": ("চুল পড়া", "চুল পড়ে যাওয়া",),
    "half-life": ("অর্ধ-জীবন", "অর্ধায়ু",),
    "hallucinations": ("মতিভ্রম", "হ্যালুসিনেশন",),
    "hands": ("হাত",),
    "hands and feet": ("হাত ও পা",),
    "happiness hormone": ("সুখের হরমোন",),
    "harmful": ("ক্ষতিকর",),
    "hashimoto's": ("হাশিমোটোস",),
    "hashimoto's disease": ("হাশিমোটো-এর রোগ",),
    "hashimoto's thyroiditis": ("হাশিমোটো থাইরয়েডাইটিস", "হাশিমোটো'স থাইরয়েডাইটিস",),
    "hay fever": ("খড় জ্বর",),
    "head": ("মাথ", "মাথা",),
    "head injury": ("মাথার আঘাত",),
    "headache": ("মাথা ব্যথা", "মাথা ব্যাথা", "মাথাব্যথা",),
    "headache and nausea": ("মাথা ব্যথা এবং বমি বমি ভাব",),
    "health": ("স্বাস্থ্য",),
    "health risks": ("স্বাস্থ্য ঝুঁকি",),
    "healthcare": ("স্বাস্থ্যসেবা",),
    "healthcare professionals": ("স্বাস্থ্যসেবা পেশাদার",),
    "healthcare provider": ("স্বাস্থ্যসেবা প্রদানকারী", "স্বাস্থ্যসেবা প্রদানকারীর",),
    "healthcare providers": ("স্বাস্থ্যসেবা প্রদানকারী",),
    "heart": ("হার্ট", "হৃদ", "হৃদপিণ্ড", "হৃদপিন্ড", "হৃদযন্ত্র", "হৃদয়", "হৃৎপিণ্ড", "হৃৎপিন্ড",),
    "heart and lungs": ("হৃদয় এবং ফুসফুস",),
    "heart attack": ("হার্ট অ্যাটাক", "হার্ট অ্যাটাকের", "হৃদরোগের আক্রমণ",),
    "heart attack or stroke": ("হার্ট অ্যাটাক বা স্ট্রোকের",),
    "heart attacks": ("হার্ট অ্যাটাক",),
    "heart conditions": ("হার্টের অবস্থা",),
    "heart disease": ("হৃদপিণ্ড ব্যাধি", "হৃদযন্ত্রের  বৈকল্য", "হৃদয় রোগ", "হৃদরোগ",),
    "heart failure": ("হার্ট ফেইলিউর", "হার্ট ফেইলিওর", "হৃদযন্ত্রের  বৈকল্য", "হৃদযন্ত্রের দুর্বলতা", "হৃদযন্ত্রের ব্যর্থতা",),
    "heart function": ("হৃদযন্ত্রের কার্যক্ষমতা",),
    "heart problems": ("হার্টের সমস্যা",),
    "heart pumping": ("হার্টের পাম্পিং",),
    "heart rate": ("হার্ট রেট", "হৃদপিণ্ড", "হৃদস্পন্দন",),
    "heart rate problems": ("হৃদস্পন্দনের সমস্যা",),
    "heart valve replacement": ("হৃৎপিন্ডের ভালভ প্রতিস্থাপন",),
    "heartburn": ("অম্বল", "বুকজ্বালা",),
    "heavy jaw": ("চোয়াল ভারী হওয়া",),
    "height": ("উচ্চতা",),
    "height increase": ("উচ্চতা বৃদ্ধি।",),
    "helicobacter pylori": ("হেলিকোব্যাক্টর পাইলরি", "হেলিকোব্যাক্টর পাইলোরি",),
    "hematuria": ("হেমাটুরিয়া",),
    "hemodialysis": ("হেমোডায়ালাইসিস",),
    "hemodynamic": ("হেমোডাইনামিক",),
    "hemodynamic effects": ("হেমোডাইনামিক প্রভাব",),
    "hemolytic anemia": ("হিমোলাইটিক অ্যানিমিয়া", "হেমোলাইটিক অ্যানিমিয়া",),
    "hemophilia a": ("হিমোফিলিয়া এ",),
    "hemorrhage": ("রক্তক্ষরণ",),
    "hepatic coma": ("হেপাটিক কোমা",),
    "hepatic impairment": ("হেপাটিক বৈকল্য",),
    "hepatitis": ("হেপাটাইটিস",),
    "hepatitis b": ("হেপাটাইটিস বি",),
    "hereditary": ("বংশগত।",),
    "hering body": ("হেরিং বডি",),
    "hering's body": ("হেরিং বডি",),
    "herpes labialis": ("হারপিস ল্যাবিয়ালিস",),
    "high blood potassium": ("উচ্চ রক্তের পটাসিয়াম",),
    "high blood pressure": ("উচচ রক্তচাপ", "উচ্চ  রক্তচাপ", "উচ্চ রক্তচাপ", "উচ্চরক্তচাপ", "উচ্চ্ রক্তচাপ",),
    "high cholesterol": ("উচ্চ  কোলেস্টেরল", "উচ্চ কোলেস্টেরল",),
    "high concentration": ("উচ্চ ঘনত্ব",),
    "high density lipoprotein": ("ডেনসিটি লিপোপ্রোটিন",),
    "high dose": ("উচ্চ ডোজ",),
    "high potassium": ("উচ্চ পটাসিয়াম",),
    "high pressure": ("উচ্চ চাপ",),
    "hippocampus": ("হিপ্পোক্যাম্পাস",),
    "hips": ("নিতম্ব",),
    "hirsutism": ("হিরসুটিজম",),
    "histamine": ("হিস্টামিন",),
    "histamines": ("হিস্টামাইনস",),
    "hiv": ("এইচআইভি",),
    "hiv infection": ("এইচআইভি সংক্রমণ",),
    "hiv-related weight loss": ("এইচআইভি-সম্পর্কিত ওজন হ্রাস",),
    "hives": ("আমবাত",),
    "holbar": ("হোলবাড়",),
    "homeostasis": ("হোমিওস্টেসিস",),
    "hookworms": ("হুকওয়ার্ম",),
    "hormonal deficiencies": ("হরমোনাল ঘাটতি",),
    "hormonal deficiency": ("হরমোনের ঘাটতি",),
    "hormonal problems": ("হরমোনজনিত সমস্যা",),
    "hormone availability": ("হরমোনের প্রাপ্যতা",),
    "hormone dependence": ("হরমোন নির্ভরতা",),
    "hormone injections": ("হরমোন ইনজেকশন",),
    "hormone levels": ("হরমোনের মাত্রা",),
    "hormone replacement": ("হরমোন প্রতিস্থাপন",),
    "hormone replacement therapy": ("হরমোন প্রতিস্থাপন চিকিৎসা", "হরমোন প্রতিস্থাপন থেরাপি",),
    "hormone secretion": ("হরমোন ক্ষরণ", "হরমোন নিঃসরণ", "হরমোন নিঃসরণ।",),
    "hormone synthesis": ("হরমোনের সংশ্লেষণ",),
    "hormone therapy": ("হরমোন থেরাপি",),
    "hormones": ("হরমোন",),
    "hospital": ("হাসপাতাল",),
    "hot flash": ("হট ফ্ল্যাশ",),
    "hpa axis": ("এইচপিএ অক্ষ",),
    "human": ("মানব।",),
    "hydatid disease": ("হাইডাটিড রোগ",),
    "hydration": ("হাইড্রেশন",),
    "hydrocodone": ("হাইড্রোকোডোন",),
    "hydrolysis": ("হাইড্রোলাইসিস",),
    "hydroxyapatite crystals": ("হাইড্রোক্সাপাটাইট স্ফটিক",),
    "hyper-reactivity": ("হাইপার-রিঅ্যাকটিভিটি",),
    "hyperaldosteronism": ("হাইপারলডোস্টেরনিজম", "হাইপারালডোস্টেরনিজম",),
    "hyperandrogenism": ("হাইপারঅ্যান্ড্রোজেনিজম",),
    "hypercalcemia": ("হাইপারক্যালসিমিয়া", "হাইপারক্যালসেমিয়া",),
    "hypercholesterolemia": ("হাইপারকোলেস্টেরোলেমিয়া",),
    "hyperglycemia": ("হাইপারগ্লাইসেমিয়া", "হাইপারগ্লাইসেমিয়া",),
    "hyperkalemia": ("হাইপারক্যালেমিয়া",),
    "hyperosmolality": ("হাইপারোসমোল্যালিটি",),
    "hyperparathyroidism": ("হাইপারপ্যারাথাইরয়ডিজম", "হাইপারপ্যারাথাইরয়েডিজম",),
    "hyperprolactinemia": ("হাইপারপ্রােল্যাকটিনেমিয়া", "হাইপারপ্রোল্যাকটিনেমিয়া", "হাইপারপ্রোল্যাক্টিনেমিয়া",),
    "hypersecretion": ("হাইপারসিক্রেশন",),
    "hypersecretory disease": ("অতিরিক্ত ক্ষরণজনিত রোগ",),
    "hypersensitivity": ("অতি সংবেদনশীলতা", "অতিসংবেদনশীলতা",),
    "hypertension": ("উচ্চ রক্তচাপ", "হাইপারটেনশন",),
    "hyperthermia": ("হাইপারথার্মিয়া",),
    "hyperthyroidism": ("হাইপারথাইরয়ডিজম", "হাইপারথাইরয়েডিজম",),
    "hypertonicity": ("হাইপারটোনিসিটি",),
    "hypnotic": ("সম্মোহনী", "হিপনোটিক",),
    "hypo-parathyroidism": ("হাইপো-প্যারাথাইরয়েডিজম",),
    "hypoadrenalism": ("হাইপোঅ্যাড্রেনালিজম",),
    "hypocalcemia": ("হাইপোক্যালসেমিয়া",),
    "hypoglycemia": ("হাইপোগ্লাইসেমিয়া", "হাইপোগ্লাইসেমিয়া",),
    "hypogonadism": ("হাইপোগোনাডিজম",),
    "hypokalemia": ("হাইপোক্যালেমিয়া",),
    "hypomagnesemia": ("হাইপোম্যাগনেসিমিয়া",),
    "hyponatremia": ("হাইপোনাট্রেমিয়া", "হাইপোনেট্রেমিয়া",),
    "hypoosmolality": ("হাইপোসমোলালিটি",),
    "hypoparathyroidism": ("হাইপোপ্যারাথাইরয়েডিজম",),
    "hypopituitarism": ("হাইপোপিটুইটারিজম",),
    "hypotension": ("হাইপোটেনশন",),
    "hypotensive preterm infants": ("হাইপোটেনসিভ প্রিটার্ম শিশু",),
    "hypothalamic disease": ("হাইপোথ্যালামিক রোগ",),
    "hypothalamus": ("হাইপোথ্যালামাস",),
    "hypothyroidism": ("হাইপোথাইরয়ডিজম", "হাইপোথাইরয়েডিজম",),
    "hypovolemia": ("হাইপোভোলেমিয়া",),
    "hypoxia": ("হাইপোক্সিয়া",),
    "hypoxic damage": ("হাইপোক্সিক ক্ষতি",),
    "iabetis insipidus": ("য়াবেটিস ইনসিপিডাস",),
    "icterus neonatorum": ("ইকটেরাস নিওনেটরাম",),
    "illegal sale": ("বেআইনি বিক্রি",),
    "illness": ("অসুস্থতা",),
    "immune function": ("ইমিউন ফাংশন",),
    "immune system": ("ইমিউন সিস্টেম", "রোগ প্রতিরোধ ব্যবস্থা",),
    "immunoglobulin a nephropathy": ("ইমিউনোগ্লোবুলিন এ নেফ্রোপ্যাথি",),
    "immunologic": ("ইমিউনোলজিক",),
    "immunosuppressive": ("ইমিউনোসপ্রেসিভ",),
    "impotence": ("শক্তিহীনতা",),
    "improved libido": ("উন্নত লিবিডো",),
    "in erosive esophagitis": ("ইরোসিভ এসোফ্যাগাইটিসে",),
    "in the adrenal cortex": ("অ্যাড্রিনাল কর্টেক্সে",),
    "in the brain": ("মস্তিষ্কে",),
    "in the cells of the human body": ("মানবদেহের কোষে",),
    "in the gut": ("অন্ত্র",),
    "inactive": ("নিষ্ক্রিয়",),
    "inactive protein": ("নিষ্ক্রিয় প্রোটিন",),
    "inactive proteins": ("নিষ্ক্রিয় প্রোটিন",),
    "incomplete abortion": ("অসম্পূর্ণ এবরশন",),
    "increased adipose tissue": ("অ্যাডিপোজ টিস্যু বৃদ্ধি",),
    "increased blood pressure": ("রক্তচাপ বৃদ্ধি", "রক্তচাপ বেড়ে যাওয়া",),
    "increased heart rate": ("হৃদস্পন্দন বৃদ্ধি",),
    "increased or decreased heart rate": ("হৃদকম্পন বৃদ্ধি বা হ্রাস",),
    "increased risk": ("ঝুঁকি বাড়ানো",),
    "increased risk of fractures": ("ফ্র্যাকচারের ঝুঁকি বৃদ্ধি",),
    "increased secretion": ("নিঃসরণ বৃদ্ধি।",),
    "indicated": ("নির্দেশিত",),
    "indigestion": ("বদহজম",),
    "indigestion and dizziness": ("বদহজম এবং মাথা ঘোরা",),
    "industrial agriculture": ("শিল্প কৃষি",),
    "ineffective in breast milk": ("মাতৃদুগ্ধে অকার্যকর",),
    "infected tissue": ("সংক্রমিত টিস্যু",),
    "infection": ("ইনফেকশন", "সংক্রমণ",),
    "infections": ("সংক্রমণ",),
    "infections of various parts of the body": ("শরীরের বিভিন্ন অঙ্গের সংক্রমণ",),
    "infectious diarrhea": ("সংক্রামক ডায়রিয়া",),
    "infertility": ("বন্ধ্যত্ব", "বন্ধ্যাত্ব",),
    "inflamed skin": ("স্ফীত ত্বক",),
    "inflammation": ("প্রদাহ", "প্রদাহে",),
    "inflammation and relieve arthritis": ("প্রদাহ কমাতে এবং আর্থ্রাইটিস",),
    "inflammatory": ("প্রদাহজনিত",),
    "inflammatory bowel disease": ("শ্বাসনালীর প্রদাহমূলক ব্যাধি",),
    "inflammatory diseases": ("প্রদাহজনিত রোগ", "প্রদাহমূলক ব্যাধি",),
    "inflammatory response": ("প্রদাহজনক প্রতিক্রিয়া",),
    "influence": ("প্রভাব",),
    "infundibulum": ("ইনফুন্ডিবুলম",),
    "infusion": ("ইনফিউশন",),
    "infusion fluid": ("ইনফিউশন ফ্লুইড",),
    "infusions": ("ইনফিউশন",),
    "ingredients": ("উপাদান",),
    "inhaled": ("ইনহেলড",),
    "inhaler": ("ইনহেলার",),
    "inhalers": ("ইনহেলার",),
    "inherited susceptibility": ("উত্তরাধিকারসূত্রে সংবেদনশীলতা।",),
    "injectable": ("ইনজেকশনযোগ্য",),
    "injectable steroids": ("ইনজেকশনযোগ্য স্টেরয়েড",),
    "injection": ("ইঞ্জেকশন", "ইনজেকশন",),
    "injections": ("ইনজেকশন",),
    "insomnia": ("অনিদ্রা", "নিদ্রাহীনতা",),
    "instructions": ("নির্দেশনা",),
    "intake": ("গ্রহণ",),
    "intensity": ("তীব্রতা",),
    "interaction": ("ইন্টারএ্যাকশানের", "মিথষ্ক্রিয়া", "মিথস্ক্রিয়া",),
    "interactions": ("মিথস্ক্রিয়া", "মিথস্ক্রিয়া।",),
    "interventions": ("হস্তক্ষেপ",),
    "intestinal disease": ("অন্ত্রের রোগ",),
    "intestinal muscle movement": ("অন্ত্রের মাসল মুভমেন্ট",),
    "intestinal or stomach problems": ("অন্ত্রের বা পেটের সমস্যা।",),
    "intestine": ("অন্ত্র",),
    "intestines": ("অন্ত্র",),
    "intracellular stores": ("অন্তঃকোষীয় স্টোর",),
    "intranasal application": ("ইন্ট্রানাসাল প্রয়োগ",),
    "intravenous infusion": ("ইন্ট্রাভেনাস ইনফিউশন",),
    "iodine deficiency": ("আয়োডিনের অভাব",),
    "iroid gland": ("ইরয়েড গ্রন্থি",),
    "irregular heartbeat": ("অনিয়মিত  হৃদস্পন্দন", "অনিয়মিত হৃদস্পন্দন",),
    "irritable bowel syndrome": ("খিটখিটে অন্ত্র সিন্ড্রোম",),
    "irritable nodules and adenomas": ("ইরয়েড নডিউলস্ এবং অ্যাডেনোমা",),
    "irritation": ("জ্বালা",),
    "itching": ("চুলকানি",),
    "itching at the joints of the legs": ("দুই পায়ের সংযোগস্থলে চুলকানি",),
    "itching or skin irritation": ("চুলকানি বা ত্বকের জ্বালাপোড়া",),
    "itchy": ("চুলকানি",),
    "jaundice": ("জন্ডিস",),
    "jaw": ("চোয়াল",),
    "jock itch": ("জক ইচ",),
    "joint pain": ("জয়েন্টে ব্যথা", "জয়েন্টে ব্যথার",),
    "joints": ("জয়েন্ট",),
    "juvenile polyarthritis": ("জুভেনাইল পলিআর্গ্রাইটিস",),
    "keflex": ("কেফ্লেক্স",),
    "ketoacidosis": ("কিটোএসিডােসিস",),
    "kidney": ("কিডনি", "বৃক্ক", "বৃক্ক/ কিডনি", "বৃক্কের",),
    "kidney and liver dysfunction": ("বৃক্ক ও যকৃতের অকার্যকারীতা",),
    "kidney disease": ("কিডনি রোগ", "কিডনির রোগ", "বৃক্ক রোগ",),
    "kidney failure": ("কিডনি ব্যর্থতা",),
    "kidney liver": ("বৃক্ক  যকৃত",),
    "kidney or liver": ("কিডনি বা লিভার",),
    "kidney or liver disease": ("কিডনি বা লিভারের রোগের",),
    "kidney problems": ("কিডনি সমস্যা", "কিডনির সমস্যা", "বৃক্কের সমস্যা",),
    "kidney stones": ("বৃক্কে পাথর",),
    "kidney stones or gallstones": ("কিডনিতে পাথর বা পিত্তথলির পাথর",),
    "kidney tubules": ("কিডনি টিউবুল",),
    "kidney-related problems": ("কিডনি-সম্পর্কিত সমস্যাগুলির",),
    "kidneys": ("কিডনি", "কিডনি।", "কিডনিতে",),
    "kidneys and liver": ("কিডনি এবং লিভার",),
    "knees": ("হাঁটু",),
    "l-proline": ("এল-প্রোলিন",),
    "labor failure": ("প্রসব ব্যর্থতা",),
    "labor pain": ("প্রসববেদনা",),
    "labor pains": ("প্রসব বেদনা", "প্রসববেদনা",),
    "lack of adrenaline": ("অ্যাড্রেনালিনের অভাব",),
    "lactation": ("স্তন্যপান",),
    "lactose monohydrate": ("ল্যাকটোজ মনোহাইড্রেট",),
    "laparoscopic surgery": ("ল্যাপারোস্কোপিক সার্জারি",),
    "large bowel tumors": ("বৃহৎ অন্ত্রের টিউমার",),
    "large dose": ("বড় ডোজ।",),
    "large hands and feet": ("বড় হাত ও পা",),
    "large nose": ("বড় নাক",),
    "laron dwarfism": ("ল্যারন ডোয়ার্ফিজম",),
    "laryngitis": ("ল্যারিনজাইটিস",),
    "larynx": ("স্বরযন্ত্র",),
    "latent tuberculosis": ("সুপ্ত যক্ষ্মা",),
    "latex condom": ("ল্যাটেক্স কনডম",),
    "lavage saline": ("ল্যাভেটভ স্যালাইন",),
    "laxative saline": ("ল্যাক্সোটিভ স্যালাইন",),
    "laziness": ("অলসতা",),
    "left atrium": ("বাম অলিন্দ",),
    "left atrium of the heart": ("হৃৎপিণ্ডের বাম অলিন্দ",),
    "left ventricle": ("বাম ভেন্ট্রিকুল",),
    "left ventricular dysfunction": ("বাম ভেন্ট্রিকুলার কর্মহীনতা",),
    "left ventricular hypertrophy": ("বাম ভেন্ট্রিকুলার হাইপারট্রফি",),
    "letdown stimulus": ("লেটডাউন উদ্দীপনা",),
    "leukemia": ("লিউকেমিয়া",),
    "leukemias": ("লিউকেমিয়াস",),
    "leukopenia": ("লিউকোপেনিয়া",),
    "leukotriene inhibition": ("লিউকোট্রিন ইনহিবিশন",),
    "leukotrienes": ("লিউকোট্রিন", "লিউকোট্রিয়েনস",),
    "leydig cells": ("লেডিগ কোষ",),
    "libido": ("লিবিডো",),
    "libido improvement": ("লিবিডোর উন্নতি",),
    "lichen planus": ("লাইকেন প্ল্যানাস",),
    "lichen sclerosus": ("লাইকেন স্ক্লেরোসাস",),
    "limb development": ("অঙ্গপ্রত্যঙ্গের বিকাশ",),
    "limitations": ("সীমাবদ্ধতা",),
    "limitations of use": ("ব্যবহারের সীমাবদ্ধতা",),
    "lipodystrophy": ("লিপোডিস্ট্রফি",),
    "lips": ("ঠোঁট",),
    "liver": ("যকৃত", "যকৃৎ", "লিভার",),
    "liver and kidney concerns": ("লিভার এবং কিডনির উদ্বেগ",),
    "liver and kidney disease": ("লিভার  ও  কিডনির  রোগ",),
    "liver and kidneys": ("লিভার এবং কিডনি",),
    "liver and pancreas": ("লিভার এবং প্যানক্রিয়াস",),
    "liver cells": ("যকৃতের কোষ",),
    "liver damage": ("লিভারের ক্ষতি",),
    "liver disease": ("যকৃত রোগ", "যকৃতের রোগ", "লিভার রোগ", "লিভারের রোগ",),
    "liver failure": ("লিভারের ব্যর্থতা",),
    "liver function": ("লিভার ফাংশন",),
    "liver function abnormalities": ("লিভার ফাংশন অস্বাভাবিকতা",),
    "liver impairment": ("যকৃতের বৈকল্য",),
    "liver problems": ("লিভার সমস্যা", "লিভারের সমস্যা",),
    "liver scarring": ("লিভারের দাগ",),
    "livestock": ("গবাদি পশু",),
    "localized abdominal pain": ("লোকালাইজড এ্যাবডোমিনাল পেইন",),
    "loss of appetite": ("ক্ষুধা হ্রাস", "ক্ষুধামান্দ্য",),
    "loss of balance": ("ভারসাম্য হারানো",),
    "loss of cardiovascular efficiency": ("কার্ডিওভাসকুলার দক্ষতার ক্ষতি",),
    "loss of energy": ("শক্তি হ্রাস",),
    "loss of libido": ("কামনা হ্রাস",),
    "loss of muscle mass": ("পেশী ভর হ্রাস",),
    "loss of muscle strength": ("পেশী শক্তি হ্রাস",),
    "lotion": ("লোশন",),
    "love": ("ভালবাসা",),
    "low blood potassium": ("নিম্ন রক্তের পটাসিয়াম",),
    "low blood pressure": ("নিম্ন রক্তচাপ", "নিম্নরক্তচাপ", "রক্তচাপ কমা", "রক্তচাপ কমে যাওয়া", "লো ব্লাড প্রেসার",),
    "low cardiac output": ("কম কার্ডিয়াক আউটপুট",),
    "low libido": ("নিম্ন লিবিডো",),
    "low sex drive": ("কম যৌন চাহিদা",),
    "low sodium": ("নিম্ন সোডিয়াম",),
    "low testosterone": ("লো টেস্টোস্টেরন",),
    "lower abdomen": ("তলপেটে",),
    "lower abdominal pain": ("তলপেটে ব্যথা",),
    "lozenges": ("লজেন্স",),
    "lump": ("পিণ্ড",),
    "lung cancer": ("ফুসফুসের ক্যান্সার",),
    "lung disease": ("ফুসফুসের রোগ",),
    "lung diseases": ("ফুসফুসের রোগ",),
    "lung problems": ("ফুসফুসের সমস্যার",),
    "lungs": ("ফুসফুস",),
    "lungs and respiratory system": ("ফুসফুস এবং শ্বাসতন্ত্র",),
    "lungs skin": ("ফুসফুসে ত্বকে",),
    "lupus": ("লুপাস",),
    "lyme disease": ("লাইম রোগ",),
    "lymphocyte": ("লিম্ফোসাইট",),
    "lymphomas": ("লিম্ফোমাস",),
    "lymphomas and leukemias": ("লিম্ফোমাস এবং লিউকেমিয়াস",),
    "magnesium": ("ম্যাগনেসিয়াম",),
    "major depressive disorder": ("মেজর ডিপ্রেসিভ ডিসঅর্ডার",),
    "malaria": ("ম্যালেরিয়া", "ম্যালেরিয়া",),
    "male genitalia": ("পুরুষ যৌনাঙ্গ",),
    "male genitals": ("পুরুষদের যৌনাঙ্গ",),
    "male puberty problems": ("পুরুষদের বয়ঃসন্ধি সমস্যা",),
    "male reproductive organs": ("পুরুষ প্রজনন অঙ্গ", "পুরুষদের প্রজনন অঙ্গ",),
    "mammary gland": ("মধ্যেস্তন্যপায়ী গ্রন্থি", "মধ্স্তন্যপায়ী গ্রন্থি", "স্তনগ্রন্থি",),
    "mammary glands": ("স্তনগ্রন্থি", "স্তন্যপায়ী গ্রন্থি",),
    "management": ("পরিচালনা", "ব্যবস্থাপনা",),
    "mania": ("ম্যানিয়া",),
    "masculinization": ("পুরুষালিকরণ",),
    "maternal care": ("মাতৃ লালন-পালন",),
    "measles": ("হাম",),
    "medical": ("মেডিকেল",),
    "medical advice": ("চিকিৎসা  পরামর্শ", "চিকিৎসা পরামর্শ",),
    "medical condition": ("মেডিকেল অবস্থা",),
    "medical emergency": ("মেডিকেল ইমার্জেন্সি",),
    "medical history": ("চিকিৎসা ইতিহাস",),
    "medical officer": ("মেডিকেল অফিসার",),
    "medical use": ("চিকিৎসায় ব্যবহার",),
    "medication": ("ওষুধ", "ঔষধ",),
    "medications": ("ওষুধ",),
    "medicine": ("ওষুধ", "ঔষধ",),
    "medicine dosage": ("ওষুধ ডোজ",),
    "medicines": ("ওষুধ",),
    "medicines lung infections": ("ঔষধ ফুসফুস সংক্রমণ",),
    "medulla oblongata": ("মেডুলা অবলংগাটা",),
    "medulla oblongata of the brain": ("মস্তিষ্কের মেডুলা অবলংগাটা",),
    "medullary center": ("মেডুলারি সেন্টার",),
    "medullary portion": ("মেডুলারি অংশ",),
    "medullary thyroid cancer": ("মেডুলারি থাইরয়েড ক্যান্সার",),
    "melasma": ("মেলাসমা",),
    "melatonin": ("মেলাটোনিন",),
    "membrane": ("ঝিল্লি",),
    "memory problems": ("স্মৃতিশক্তির সমস্যা",),
    "meningitis": ("মেনিনজাইটিস",),
    "menopause": ("মেনোপজ",),
    "menorrhagia": ("মেনোরেজিয়া",),
    "menstrual cramps": ("মাসিক ক্র্যাম্প",),
    "menstrual cycle": ("মাসিক চক্র",),
    "menstrual cycle problems": ("মাসিক চক্রের সমস্যা",),
    "menstrual disorders": ("মাসিকের ব্যাঘাত",),
    "menstrual irregularities": ("মাসিকের বাধা",),
    "menstrual pain": ("ঋতুস্রাব  জনিত  ব্যথা",),
    "menstrual problems": ("ঋতুস্রাবজনিত সমস্যা", "ঋতুস্রাবের সমস্যা",),
    "menstruation": ("ঋতুস্রাব",),
    "mental and physical problems": ("মানসিক ও শারীরিক সমস্যা",),
    "mental behavior": ("মানসিক আচরণ",),
    "mental disorders": ("মানসিক ব্যাধি",),
    "mental health": ("মানসিক স্বাস্থ্য",),
    "mental health problems": ("মানসিক স্বাস্থ্য সমস্যা",),
    "mental illness": ("মানসিক রোগ",),
    "mental illnesses such as depression": ("মানসিক রোগ যেমন হতাশা",),
    "mental problems": ("মানসিক সমস্যা",),
    "mental retardation": ("মানসিক বঞ্চনা।",),
    "mental state": ("মানসিক অবস্থা",),
    "mental symptoms": ("মানসিক উপসর্গ",),
    "message communication": ("বার্তা যোগাযোগ",),
    "meta-analysis": ("মেটা-বিশ্লেষণ",),
    "metabolic": ("বিপাকীয়",),
    "metabolic acidosis": ("বিপাকীয় অ্যাসিডোসিস",),
    "metabolic process": ("বিপাকীয় প্রক্রিয়া",),
    "metabolic processes": ("বিপাকের প্রক্রিয়া",),
    "metabolism": ("বিপাক",),
    "metabolismmolecule": ("বিপাকঅণু",),
    "metabolites": ("মেটাবোলাইট",),
    "metallic taste": ("ধাতব স্বাদ",),
    "metrorrhagia": ("মেট্রোরেজিয়া",),
    "microcirculation": ("মাইক্রোসার্কুলেশন",),
    "microglia inflammation": ("মাইক্রোগ্লিয়ার প্রদাহ",),
    "microorganisms": ("অণুজীব",),
    "migraine": ("মাইগ্রাইন", "মাইগ্রেন",),
    "migraine headache": ("মাইগ্রেনের মাথাব্যথার",),
    "migraine pain": ("মাইগ্রেনের ব্যথা",),
    "migraines": ("মাইগ্রেন",),
    "mild hemophilia a": ("হালকা হিমোফিলিয়া এ",),
    "milk": ("দুধ",),
    "milk letdown problems": ("দুধ নির্গমনের সমস্যা",),
    "mimicry": ("অনুকরণ।",),
    "mineralocorticoids": ("মিনারেলোকর্টিকয়েড",),
    "minor wounds": ("ক্ষুদ্র ক্ষতগুলি",),
    "miscarriage": ("গর্ভস্রাব",),
    "miss": ("মিস",),
    "missed dose": ("ডোজ মিস", "মিস ডোজ", "মিসড ডোজ", "মিসড ডোজটি",),
    "modulation": ("মডুলেশন",),
    "molecular isoform": ("আণবিক আইসোফর্ম",),
    "molecule": ("অণু",),
    "monitoring": ("নিরীক্ষণ", "পর্যবেক্ষণ",),
    "mood": ("মেজাজ",),
    "mood disorders": ("মুড ডিসঅর্ডার", "মেজাজজনিত ব্যাধি",),
    "mood problems": ("মেজাজজনিত সমস্যা",),
    "mood swings": ("মেজাজ পরিবর্তন",),
    "moon face": ("মুন ফেস",),
    "motor control": ("মোটর নিয়ন্ত্রণ",),
    "mouth": ("মুখ", "মুখগহ্বর",),
    "mouth sores": ("মুখের ঘা",),
    "mouthwash": ("মাউথওয়াশ",),
    "mucus": ("মিউকাস", "শ্লেষ্মা",),
    "multiple myeloma": ("মাল্টিপল মাইলোমা",),
    "muscle": ("পেশী",),
    "muscle aches": ("পেশী ব্যথা",),
    "muscle development": ("পেশীর বিকাশ",),
    "muscle loss": ("পেশী ক্ষয়",),
    "muscle mass": ("পেশী ভর",),
    "muscle mass gain": ("পেশী ভর বৃদ্ধি",),
    "muscle pain": ("পেশী  ব্যথা", "পেশী ব্যথা", "পেশী ব্যাথা", "পেশী যন্ত্রণা", "মস্তিষ্কের ব্যথা",),
    "muscle pain and weakness": ("পেশী ব্যথা এবং দুর্বলতা",),
    "muscle relaxants": ("পেশী শিথিল",),
    "muscle wasting": ("মাংসপেশির ক্ষয়",),
    "muscle weakness": ("পেশী দুর্বলতা",),
    "muscles": ("পেশি", "পেশী", "মাংসপেশি", "মাংসপেশী",),
    "myocardial dysfunction": ("মায়োকার্ডিয়াল ডিসফাংশন",),
    "myocardial infarction": ("মায়োকার্ডিয়াল ইনফার্কশন",),
    "myocardium": ("মায়োকার্ডিয়াম",),
    "myoclonic seizures": ("মায়োক্লোনিক খিঁচুনি",),
    "myoepithelial cells": ("মায়োপিথেলিয়াল কোষ",),
    "myometrial cells": ("মায়োমেট্রিয়াল কোষ",),
    "myxodeme": ("ম্যাক্সোডেম",),
    "nasal congestion": ("অনুনাসিক ভিড়",),
    "nasal passages": ("অনুনাসিক প্যাসেজ",),
    "nasal polyps": ("নাকের পলিপ",),
    "nasal spray": ("অনুনাসিক স্প্রে",),
    "national poison center": ("জাতীয় বিষ কেন্দ্র",),
    "natriuresis": ("ন্যাট্রিউরিসিস",),
    "nausea": ("বমি বমি ভাব", "বমিবমি ভাব", "বমিভাব",),
    "nausea and vomiting": ("বমি বমি ভাব এবং বমি",),
    "nebulizer": ("নেবুলাইজার",),
    "neck": ("ঘাড়",),
    "necrosis": ("নেক্রোসিস",),
    "negative feedback": ("নেতিবাচক প্রতিক্রিয়া",),
    "nephron": ("নেফ্রন",),
    "nephrosis": ("নেফ্রোসিস",),
    "nephrotic syndrome": ("নেফ্রোটিক সিনড্রোম",),
    "nerve": ("স্নায়",),
    "nerve cells": ("স্নায়ু কোষ",),
    "nerve damage": ("স্নায়ুর ক্ষতি",),
    "nerve pain": ("স্নায়ু  ব্যথা",),
    "nerve problems": ("নার্ভ সমস্যা",),
    "nerve signals": ("স্নায়ু সংকেত",),
    "nerve terminal": ("স্নায়ু টার্মিনাল",),
    "nerves": ("স্নায়ু",),
    "nerves and muscles of the body": ("শরীরের স্নায়ু ও পেশী",),
    "nervous system": ("স্নায়ুতন্ত্র",),
    "nervous tissue": ("স্নায়ু টিস্যু",),
    "nettle rash": ("নেট্লর‍্যাশ",),
    "neuro-hypophysis": ("নিউরো-হাইপোফাইসিস",),
    "neurocysticercosis": ("নিউরোসিস্টিসারকোসিস",),
    "neuroeconomics": ("নিউরোইকোনমিক্স",),
    "neuroendocrine": ("নিউরোএন্ডোক্রাইন",),
    "neuroendocrine/carcinoid": ("নিউরোড্রোক্রিন / কার্সিনোড",),
    "neurogenic pulmonary edema": ("নিউরোজেনিক পালমোনারি শোথ",),
    "neurohypophysis": ("নিউরোহাইপোফাইসিল", "নিউরোহাইপোফাইসিস",),
    "neurological disease": ("স্নায়ুবিক রোগ",),
    "neurological function": ("স্নায়ুবিক কাজ",),
    "neuron": ("নিউরন",),
    "neurons": ("নিউরন",),
    "neuropathic pain": ("নিউরোপ্যাথিক ব্যথা",),
    "neuropathy": ("নিউরোপ্যাথি",),
    "neuropeptides": ("নিউরোপেপটাইড",),
    "neurophysin": ("নিউরোফিসিন",),
    "neuropsychiatric events": ("নিউরোসাইকিয়াট্রিক ইভেন্টস",),
    "neurosecretory cells": ("নিউরোসেক্রেটরি কোষ",),
    "neurosecretory nerves": ("নিউরোসেক্রেটরি স্নায়ু",),
    "neurosecretory neuron": ("নিউরোসেক্রেটরি নিউরন",),
    "neurosecretory nuclei": ("নিউরোসেক্রেটরি নিউক্লিয়াস",),
    "neurosystem": ("নিউরোসিস্টেম",),
    "neurotransmission": ("নিউরোট্রান্সমিশন",),
    "neurotransmitter": ("নিউরোট্রান্সমিটার",),
    "neurotransmitters": ("নিউরোট্রান্সমিটার",),
    "night awakenings": ("রাতের জাগরণ",),
    "nightmares": ("দুঃস্বপ্ন",),
    "nipples/areola": ("স্তনবৃন্ত/আরিওলা",),
    "nitric oxide": ("নাইট্রিক অক্সাইড",),
    "nociseptic cream/solution": ("ন্টিসেপটিক ক্রিম/সলিউশন",),
    "nocturia": ("নকটুরিয়া",),
    "nocturnal enuresis": ("নিশাচর এনুরেসিস",),
    "nocturnal myoclonus": ("নিশাচর মায়োক্লোনাস",),
    "nodule removal": ("নোডিউল অপসারণ",),
    "non-sedative": ("নন-সিডেটিভ",),
    "nonapeptide": ("ননাপেপটাইড",),
    "nonseptic conditions": ("ননসেপটিক অবস্থা",),
    "nonvertebral fractures": ("ননভার্টেব্রাল ফ্র্যাকচার",),
    "noonan syndrome": ("নুনান সিন্ড্রোম",),
    "norepinephrine": ("নরপাইনফ্রাইন", "নরপাইনফ্রিন",),
    "nose": ("নাক", "নাসিকা",),
    "nose damage": ("নাকের ক্ষতি",),
    "nsaids": ("এনএসএআইডি",),
    "nuclear factor kappa b": ("নিউক্লিয়ার ফ্যাক্টর কাপ্পা বি",),
    "numbness": ("অসাড় অবস্থা", "অসাড়তা",),
    "nursing": ("নার্সিং",),
    "obsessive compulsive disorder": ("অবসেসিভ কম্পালসিব ব্যাধি",),
    "obsessive-compulsive disorder": ("অবসেসিভ-বাধ্যতামূলক ব্যাধি",),
    "ocular herpes simplex": ("অকুলার হারপিস সিমপ্লেক্স",),
    "oil": ("তৈল",),
    "oily skin": ("তৈলাক্ত ত্বক",),
    "ointment": ("মলম",),
    "ointments": ("মলম",),
    "okacet allergy itching": ("ওকাসেট অ্যালার্জি চুলকানি",),
    "old world monkey": ("ওল্ড ওয়ার্ল্ড বানর",),
    "on the skin": ("ত্বকে",),
    "onset of action": ("কর্মের সূচনা",),
    "open-angle glaucoma": ("ওপেন-এঙ্গেল গ্লুকোমা",),
    "operation": ("অপারেশন",),
    "ophthalmology": ("চক্ষুবিদ্যা",),
    "opioid": ("ওপিওড",),
    "opioids": ("ওপিওড", "ওপিওডস",),
    "opium alkaloid": ("অপিয়াম অ্যালকালয়েড", "আফিম অ্যালকালয়েড",),
    "opium alkaloids": ("অপিয়াম অ্যালকালয়েড",),
    "optic nerve": ("অপটিক স্নায়ু",),
    "oral": ("ওরাল",),
    "oral administration": ("মৌখিক সেবন",),
    "oral bioavailability": ("মৌখিক জৈব উপলভ্যতা",),
    "oral candidiasis": ("মুখগহ্বরের ক্যান্ডিডিয়াসিস",),
    "oral cavity": ("মুখগহ্বর",),
    "oral contraceptives": ("মৌখিক গর্ভনিরোধক",),
    "oral drops": ("ওরাল ড্রপ",),
    "oral intake": ("মৌখিক গ্রহণ",),
    "oral moniliasis": ("ওরাল মনিলিয়াসিস",),
    "oral pills": ("মৌখিক বড়ি",),
    "oral tablet": ("ওরাল ট্যাবলেট",),
    "oral tablets": ("ওরাল ট্যাবলেট",),
    "oral thrush": ("ওরাল থ্রাস", "মৌখিক থ্রেশ",),
    "orally": ("মৌখিকভাবে",),
    "orally administered": ("মৌখিকভাবে পরিচালনা",),
    "organ damage": ("অঙ্গ-প্রত্যঙ্গের ক্ষতি",),
    "organ transplantation": ("অঙ্গ প্রতিস্থাপন",),
    "organs": ("অঙ্গ", "অঙ্গ-প্রত্যঙ্গের", "অঙ্গপ্রত্যঙ্গে",),
    "orthostatic hypotension": ("অর্থোস্ট্যাটিক হাইপোটেনশন",),
    "osmolality": ("অসমোলালিটি",),
    "osmolarity": ("অসমোলারিটি",),
    "osteoarthritis": ("অস্টিওআথ্রাইটিস", "অস্টিওআর্থারাইটিস",),
    "osteoblast": ("অস্টিওব্লাস্ট",),
    "osteoclast": ("অস্টিওক্লাস্ট",),
    "osteoclasts": ("অস্টিওক্লাস্ট",),
    "osteogenesis": ("অষ্টিওজেনেসিস",),
    "osteomalacia": ("অষ্টিওম্যালাসিয়া", "অস্টিওম্যালেসিয়া",),
    "osteon": ("অস্টিওন",),
    "osteonecrosis": ("অস্টিওনেক্রোসিস",),
    "osteoporosis": ("অষ্টিওপরোসিস", "অস্টিওপরোসিস", "অস্টিওপরোসিসের", "অস্টিওপোরেসিস", "অস্টিওপোরোসিস",),
    "other drugs": ("অন্যান্য ওষুধ",),
    "otitis media": ("ওটাইটিস মিডিয়া", "ওটিটিস মিডিয়া",),
    "out of balance": ("ভারসাম্যের বাইরে",),
    "ovarian cancer": ("ডিম্বাশয় ক্যান্সার",),
    "ovariectomy": ("ওভারেক্টমি",),
    "ovaries": ("ডিম্বাশয়",),
    "ovary": ("ডিম্বাশয়",),
    "over-the-counter medications": ("ওভার-দ্য-কাউন্টার ওষুধ",),
    "overcoming": ("কাটিয়ে ওঠা",),
    "overdose": ("অতিরিক্ত মাত্রা", "অতিরিক্ত মাত্রায় সেবন", "ওভারডোজ",),
    "overdose symptoms": ("অতিরিক্ত মাত্রার লক্ষণ",),
    "oxygen supply": ("অক্সিজেন সরবরাহ",),
    "oxytocin": ("অক্সিটোসিন",),
    "oxytocin production": ("অক্সিটোসিন উত্পাদন",),
    "oxytocin release": ("অক্সিটোসিন নিঃসরণ",),
    "paget's disease": ("পেজেটস ডিজিজ",),
    "paget's disease of bone": ("পেজেটের হাড়ের রোগ", "প্যাজেট’স ডিজিজ অফ বোন",),
    "pain": ("ব্যথা", "ব্যাথা",),
    "pain and inflammation": ("ব্যথা এবং প্রদাহজনক", "ব্যথা এবং প্রদাহের",),
    "painful menstrual cramps": ("বেদনাদায়ক মাসিক ট্র্যাশগুলি",),
    "painkillers": ("ব্যথানাশক",),
    "pair-bonding in voles": ("ভোলে জোড়া-বন্ধন",),
    "palpitations": ("পালপিটেসন", "বুক ধড়পড় করা",),
    "pancreas": ("অগ্ন্যাশয়", "প্যানক্রিয়া", "প্যানক্রিয়াস",),
    "pancreatic tumors": ("অগ্ন্যাশয়ের টিউমার",),
    "pancreatitis": ("অগ্ন্যাশয়ের প্রদাহ", "প্যানক্রিয়াটাইটিস",),
    "panhypopituitarism": ("প্যানহাইপোপিটুইটারিজম",),
    "panic attacks": ("আতঙ্কিত আক্রমণ", "প্যানিক অ্যাটাক", "প্যানিক আক্রমণ",),
    "panic disorder": ("প্যানিক  ব্যাধি", "প্যানিক ডিসঅর্ডার",),
    "papillary thyroid cancer": ("প্যাপিলারি থাইরয়েড ক্যান্সার",),
    "paracrine signaling": ("প্যারাক্রাইন সংকেত",),
    "parathyroid gland": ("প্যারাথাইরয়েড গ্রন্থি",),
    "parathyroid gland tumor": ("প্যারাথাইরয়েড গ্রন্থির টিউমার",),
    "parathyroid glands": ("প্যারাথাইরয়েড গ্রন্থি",),
    "parathyroid hormone": ("প্যারাথাইরয়েড হরমোন",),
    "paresthesia": ("প্যারেসথেসিয়া",),
    "parkinson's": ("পারকিনসন", "পারকিনসন্স", "পার্কিনসন্স",),
    "parkinson's disease": ("পারকিনসন রোগ", "পারকিনসন'স রোগ", "পারকিনসন্স ডিজিজ", "পারকিনসন্স রোগ", "পার্কিনসন রোগ", "পার্কিনসন'স রোগ",),
    "patent": ("পেটেন্ট",),
    "pathophysiology": ("প্যাথোফিজিওলজি",),
    "patient": ("রোগী",),
    "pea-sized": ("মটর-আকার",),
    "pediatric dosage": ("পেডিয়াট্রিক ডোজ",),
    "peeling skin": ("ত্বকের খোসা ছাড়ানো",),
    "pegvisomant": ("পেগভিসোম্যান্ট",),
    "pelvis": ("পেলভিস",),
    "pemphigus vulgaris": ("পেমফিগাস ভালগারিস",),
    "penicillin": ("পেনিসিলিন",),
    "penicillin-binding protein": ("পেনিসিলিন-বাইন্ডিং প্রোটিন",),
    "penis": ("লিঙ্গ",),
    "peptic ulcer": ("পেপটিক  আলসার", "পেপটিক আলসার", "পেপ্টিক আলসার",),
    "peptic ulcer disease": ("পেপটিক আলসার রোগ",),
    "peptide": ("পেপটাইড",),
    "peptide hormones": ("পেপটাইড হরমোন",),
    "peptides": ("পেপটাইড",),
    "peptidoglycan": ("পেপটিডোগ্লাইকান",),
    "period": ("পিরিয়ড",),
    "period pain": ("পিরিয়ডের ব্যথা",),
    "perioperative polyuria": ("পেরিওপারেটিভ পলিউরিয়া",),
    "perioral dermatitis": ("পেরিওরাল ডার্মাটাইটিস",),
    "peripheral activity": ("পেরিফেরাল কার্যকলাপ",),
    "peripheral arterial disease": ("পেরিফেরাল আর্টারিয়াল ডিজিজ", "পেরিফেরাল ধমনী রোগ",),
    "peripheral artery disease": ("পেরিফেরাল ধমনী রোগ",),
    "peripheral circulation": ("পেরিফেরাল সঞ্চালন",),
    "peripheral edema": ("পেরিফেরাল ইডিমা",),
    "peritonitis": ("পেরিটোনাইটিস",),
    "permitted concentrations": ("অনুমোদিত ঘনত্ব",),
    "persistence": ("স্থায়ী হওয়া",),
    "pets": ("পোষা প্রাণী",),
    "phantom limb pain": ("ফ্যান্টম অঙ্গ ব্যথা",),
    "pharmaceutical": ("ফার্মাসিউটিক্যাল",),
    "pharmacist": ("ফার্মাসিস্ট",),
    "pharmacological": ("ফার্মাকোলজিক্যাল",),
    "pharmacology": ("ফার্মাকোলজি",),
    "pharyngitis": ("ফ্যারিঞ্জাইটিস", "ফ্যারিনজাইটিস",),
    "phenylketonuria": ("ফেনাইলকেটোনুরিয়া",),
    "phenytoin": ("ফেনিটয়েন",),
    "pheochromocytoma": ("ফিওক্রোমাসাইটোমা", "ফিওক্রোমোসাইটোমা",),
    "phlegm center of the brain": ("মস্তিষ্কের কফ সেন্টার",),
    "phlegm suppressant": ("কফ দমন",),
    "phosphate": ("ফসফেট",),
    "phospholipase c": ("ফসফোলিপেস সি",),
    "phosphorylase kinase": ("ফসফরিলেজ কিনেস",),
    "physical": ("শারীর",),
    "physical activity": ("শারীরিক কার্যকলাপ", "শারীরিক ক্রিয়াকলাপ",),
    "physical and social disruption": ("শারীরিক এবং সামাজিক বিঘ্ন",),
    "physical competition": ("শারীরিক প্রতিযোগিতা",),
    "physical dependence": ("শারীরিক নির্ভরতা",),
    "physical disturbance": ("শারীরিক বিঘ্ন",),
    "physical fitness": ("শারীরিক সুস্থতা",),
    "physical growth": ("শারীরিক বৃদ্ধি",),
    "physical problems": ("শারীরিক সমস্যা",),
    "physical symptoms": ("শারীরিক উপসর্গ", "শারীরিক ঊপসর্গ",),
    "physiological function": ("শারীরিক ক্রিয়া",),
    "physiological response": ("শারীরবৃত্তীয় প্রতিক্রিয়া",),
    "physiological stimulation": ("শারীরবৃত্তীয় উদ্দীপনা",),
    "physiological stress": ("শারীরবৃত্তীয় চাপ",),
    "physiotherapy": ("ফিজিওথেরাপি",),
    "phytoestrogens": ("ফাইটোস্ট্রোজেন",),
    "phytonutrients": ("ফাইটোনিউট্রিয়েন্ট",),
    "pill": ("পিল",),
    "pinworms": ("পিনওয়ার্ম",),
    "pituitary": ("পিটুইটারি",),
    "pituitary adenoma": ("পিটুইটারি অ্যাডেনোমা",),
    "pituitary cells": ("পিটুইটারি কোষ",),
    "pituitary disease": ("পিটুইটারি রোগ",),
    "pituitary gigantism": ("পিটুইটারি গিগান্টিজম",),
    "pituitary gland": ("পিটুইটারি গ্রন্থি", "পিটুইটারি গ্রন্থি।", "পিটুইটারি গ্রন্থির", "পিটুইটারি গ্রন্থির ক্ষতি", "পিটুইটারি গ্ল্যান্ড",),
    "pituitary gland disorders": ("পিটুইটারি গ্রন্থি ব্যাধি",),
    "pituitary gland tumors": ("পিটুইটারি গ্রন্থির টিউমার",),
    "pituitary hormone deficiency": ("পিটুইটারি হরমোনের ঘাটতি।",),
    "pituitary surgery": ("পিটুইটারি সার্জারি",),
    "pituitary tumors": ("পিটুইটারি টিউমার",),
    "placenta": ("প্লাসেন্টা", "প্ল্যাসেন্টা",),
    "placental attachment": ("প্লেসেন্টাল সংযুক্তি",),
    "plague": ("প্লেগ",),
    "plaque-type psoriasis": ("প্লেক-টাইপ সোরিয়াসিস",),
    "plasma": ("প্লাজমা", "রক্তরস",),
    "plasma elimination half-life": ("প্লাজমা নির্মূল অর্ধ-জীবন",),
    "plasma excretion": ("প্লাজমা নিঃসরণ",),
    "plasma levels": ("প্লাজমা স্তর",),
    "plasma osmolality": ("রক্তরসের অসমোলালিটি",),
    "platelets": ("প্লাটেলেটস", "প্লেটলেট",),
    "pleiotropy": ("প্লিওট্রপি",),
    "pneumatosis intestinalis": ("নিউমাটোসিস ইনটেস্টিনালিস",),
    "pneumonia": ("নিউমোনিআ", "নিউমোনিয়া", "নিউমোনিয়া",),
    "polycystic ovary syndrome": ("পলিসিস্টিক ওভারি সিনড্রোম", "পলিসিস্টিক ওভারি সিন্ড্রোম", "পলিসিস্টিক ডিম্বাশয় সিন্ড্রোম",),
    "polydipsia": ("পলিডিপসিয়া",),
    "polymenorrhea": ("পলিমেনোরিয়া",),
    "polymyalgia rheumatica": ("পলিমালজিয়া রিউম্যাটিকা",),
    "polypeptide": ("পলিপ্যাপটাইড",),
    "polypeptide hormones": ("পলিপেপটাইড হরমোন",),
    "polyuria": ("পলিউরিয়া",),
    "poor growth": ("দুর্বল বৃদ্ধি।",),
    "poor kidney function": ("দুর্বল কিডনি ফাংশন",),
    "porphyria": ("পোরফাইরিয়া",),
    "portmanteau": ("পোর্টম্যানটেউ",),
    "positive feedback": ("ইতিবাচক প্রতিক্রিয়া",),
    "posterior hypothalamus": ("পোস্টেরিয়র হাইপোথ্যালামাস",),
    "posterior pituitary": ("পোস্টেরিয়র পিটুইটারি", "পোস্টেরিয়র পিটুইটারী",),
    "posterior pituitary gland": ("পশ্চাৎ পিটুইটারি গ্রন্থি", "পোস্টেরিয়র পিটুইটারি গ্রন্থি", "পোস্টেরিয়র পিটুইটারী গ্রন্থি",),
    "postherpetic neuralgia": ("পোস্টেরপেটিক  নিউরালজিয়া",),
    "postmenopausal": ("পোস্টমেনোপাসাল",),
    "postmenopausal osteoporosis": ("পোস্টমেনোপজাল অস্টিওপরোসিস",),
    "postpartum hemorrhage": ("প্রসব-পরবর্তী রক্তপাত",),
    "postpartum thyroiditis": ("প্রসবোত্তর থাইরয়েডাইটিস",),
    "potassium deficiency": ("পটাশিয়ামের ঘাটতি",),
    "potato starch": ("আলুর স্টার্চ",),
    "povidone": ("পোভিডোন",),
    "pphn refractory": ("পিপিএইচএন রিফ্র্যাক্টরি",),
    "ppi": ("পিপিআই",),
    "prader-willi syndrome": ("প্রডার-উইলি সিনড্রোম", "প্রাডার-উইলি সিনড্রোম",),
    "pre-eclampsia": ("প্রি-এক্লাম্পসিয়া",),
    "precautions": ("সতর্কতা",),
    "pregnancy": ("গর্ভাবস্থা", "গর্ভাবস্থায়", "গর্ভাবস্থার",),
    "pregnancy-related problems": ("গর্ভাবস্থা সম্পর্কিত সমস্যা",),
    "pregnancy-risk": ("গর্ভাবস্থা-ঝুঁকি",),
    "pregnant": ("গর্ভবতী",),
    "pregnant woman": ("গর্ভবতী",),
    "premature baldness": ("অকাল টাক",),
    "premature labor": ("প্রিমেচার লেবার",),
    "premenstrual syndrome": ("প্রিমেনস্ট্রুয়াল সিনড্রোম",),
    "prescription": ("প্রেসক্রিপশ", "প্রেসক্রিপশন",),
    "prescription drug": ("প্রেসক্রিপশন ড্রাগ",),
    "prescription drugs": ("প্রেসক্রিপশন ওষুধ", "প্রেসক্রিপশন ড্রাগ",),
    "pressure sores": ("চাপ ঘা",),
    "preterm baby": ("প্রিটার্ম শিশু",),
    "preterm infants": ("প্রিটার্ম শিশু",),
    "prevention": ("প্রতিরোধ",),
    "problems controlling blood pressure": ("রক্তচাপ নিয়ন্ত্রণের সমস্যা",),
    "prodrug": ("প্রোড্রাগ",),
    "production": ("উৎপাদন",),
    "professionals": ("পেশাদারদের",),
    "prohormones": ("প্রোহরমোন",),
    "prolactin": ("প্রোল্যাক্টিন",),
    "prolactinoma": ("প্রোল্যাক্টিনোমা",),
    "prolonged use": ("দীর্ঘায়িত ব্যবহার",),
    "prominent jaw": ("বিশিষ্ট চোয়াল",),
    "propylene glycol": ("প্রোপিলিন গ্লাইকল",),
    "prostaglandin production": ("প্রোস্টাগ্ল্যান্ডিন উত্পাদন",),
    "prostate": ("প্রোস্টেট",),
    "prostate cancer": ("প্রোস্টেট ক্যান্সার", "প্রোস্টেটের ক্যান্সার",),
    "prostate gland": ("প্রোস্টেট গ্রন্থি",),
    "prostatic hypertrophy": ("প্রােস্টেটিক হাইপারট্রফি",),
    "prostatitis": ("প্রস্টাটাইটিস", "প্রোস্টাটাইটিস",),
    "protein": ("প্রোটিন",),
    "protein binding": ("প্রোটিন বন্ধন",),
    "protein bound": ("প্রোটিন আবদ্ধ",),
    "protein synthesis": ("প্রোটিন সংশ্লেষণ",),
    "proteinuria": ("প্রোটিনুরিয়া",),
    "prothrombin time": ("প্রোথ্রম্বিন টাইম",),
    "prothromycin time": ("প্রোথ্রথিন টাইম",),
    "provasopressin": ("প্রোভ্যাসোপ্রেসিন",),
    "proximal tubule": ("প্রক্সিমাল টিউবিউল",),
    "pruritus or discoloration of the tongue": ("প্রুরাইটিস বা জিহ্বার বিবর্ণতা",),
    "pseudomembranous colitis": ("সিউডোমেমব্রানাস কোলাইটিস",),
    "psoriasis": ("সোরিয়াসিস",),
    "psychosis": ("সাইকোসিস",),
    "psychosocial dwarfism": ("মনসামাজিক বামনতা",),
    "psychotherapy": ("সাইকোথেরাপি",),
    "pth secretion": ("পিটিএইচ নিঃসরণ",),
    "puberty": ("বয়ঃসন্ধি", "বয়ঃসন্ধি", "বয়ঃসন্ধি।",),
    "pulmonary": ("পালমোনারি",),
    "pulmonary edema": ("পালমোনারি শোথ",),
    "pulmonary embolism": ("পালমোনারি এমবোলিজম", "পালমোনারী এম্বলিজম",),
    "pulmonary hypertension": ("পালমোনারি হাইপারটেনশন",),
    "pulmonary tuberculosis": ("ফুসফুসীয় যক্ষ্মা",),
    "pulmonary vasculature": ("পালমোনারি ভাস্কুলেচার",),
    "pulsatile": ("স্পন্দনশীল",),
    "questions": ("প্রশ্ন",),
    "quinidine": ("কুইনিডিন",),
    "rare": ("বিরল",),
    "rash": ("ফুসকুড়ি", "র‍্যাশ",),
    "rashes": ("ফুসকুড়ি",),
    "ratio": ("অনুপাত",),
    "raynaud's disease": ("রায়নৌডের রোগ",),
    "reabsorption": ("পুনঃশোষণ", "পুনর্শোষণ",),
    "reabsorptive activity": ("পুনর্শোষণকারী কার্যকলাপ",),
    "reconstruction": ("পুনর্গঠন",),
    "rectal bleeding": ("মলদ্বার রক্তপাত",),
    "rectal or anal burning": ("রেকটাল বা মলদ্বার জ্বলন",),
    "rectum": ("মলদ্বার", "রেকটাম",),
    "red blood cells macrophages": ("লোহিত রক্তকণিকা ম্যাক্রোফেজ",),
    "red skin rash": ("লাল ত্বকের ফুসকুড়ি",),
    "redness": ("লালভাব",),
    "redness of the skin": ("ত্বকের লালত্ব",),
    "reducing stomach acid": ("পাকস্থলীর অ্যাসিড কমানো",),
    "reduction": ("হ্রাস",),
    "reflux": ("রেফ্লক্স",),
    "registered physician": ("রেজিস্টার্ড চিকিৎসক",),
    "regression": ("রিগ্রেশন",),
    "relaxation of bronchial muscles": ("শ্বাসনালীর পেশী শিথিলকরণ",),
    "relief": ("উপশম", "ত্রাণ",),
    "relief from cough": ("কাশি থেকে ত্রাণ",),
    "removal of parathyroid glands": ("প্যারাথাইরয়েড গ্রন্থির অপসারণ",),
    "renal": ("রেনাল",),
    "renal and hepatic dysfunction": ("বৃক্ক ও যকৃতের অকার্যকারীতা",),
    "renal arteries": ("রেনাল ধমনী",),
    "renal colic": ("রেনাল কোলিক",),
    "renal collecting duct": ("রেনাল সংগ্রহকারী নালী",),
    "renal impairment": ("রেনাল প্রতিবন্ধকতা",),
    "renal insufficiency": ("বৃক্কীয় অপর্যাপ্ততা",),
    "replacement": ("প্রতিস্থাপন",),
    "report": ("রিপোর্ট",),
    "reproduction": ("প্রজনন", "প্রজননের",),
    "reproductive health": ("প্রজনন স্বাস্থ্য",),
    "reproductive organs": ("প্রজনন অঙ্গ",),
    "reproductive problems": ("প্রজনন সমস্যা",),
    "reproductive system": ("প্রজনন ব্যবস্থা",),
    "reproductive tract": ("প্রজনন ট্র্যাক্ট",),
    "research": ("গবেষণা",),
    "resorption": ("পুনর্শোষণ", "রিসোর্পশন",),
    "respiratory": ("শ্বাসনালী", "শ্বাসযন্ত্র",),
    "respiratory diseases": ("শ্বাস-প্রশ্বাসের রোগ",),
    "respiratory infections": ("শ্বাসযন্ত্রের  সংক্রমণ", "শ্বাসযন্ত্রের সংক্রমণ",),
    "respiratory problems": ("শ্বাসকষ্ট", "শ্বাসযন্ত্রের সমস্যা",),
    "respiratory system": ("শ্বাসতন্ত্র", "শ্বাসযন্ত্র",),
    "respiratory tract": ("শ্বাসনালী", "শ্বাসযন্ত্র",),
    "respiratory tract infection": ("শ্বাসতন্ত্রের সংক্রমণ", "শ্বাসনালীর সংক্রমণ", "শ্বাসযন্ত্রের ইনফেকশন", "শ্বাসযন্ত্রের সংক্রমণ",),
    "respiratory tract infections": ("শ্বাসযন্ত্রের সংক্রমণ",),
    "respiratory tract inflammation": ("শ্বাসনালীতে প্রদাহ",),
    "respiratory tract obstruction": ("শ্বাসনালী প্রতিরোধ",),
    "response": ("প্রতিক্রিয়া।",),
    "restless leg syndrome": ("অস্থির লেগ সিন্ড্রোম", "রেস্টলেস লেগ সিন্ড্রোম",),
    "restlessness": ("অস্থিরতা",),
    "restoril": ("রেস্টোরিল",),
    "retina": ("রেটিনা",),
    "rhabdomyolysis": ("র‍্যাবডোমায়োলাইসিস",),
    "rheumatoid arthritis": ("রিউমাটয়েড আর্থাইটিস", "রিউমাটয়েড আর্থ্রাইটি", "রিউমাটয়েড আর্থ্রাইটিস", "রুমোটয়েড আর্থথ্রিটিস",),
    "ringworm": ("দাদ", "রিং ওয়ার্ম", "রিং ওয়ার্ম বা দাদ", "রিং কীট",),
    "risk": ("ঝুঁকি",),
    "risk of addiction": ("আসক্তির ঝুঁকি",),
    "risk of bleeding": ("রক্তপাতের ঝুঁকি",),
    "risk of death": ("মৃত্যুর ঝুঁকি",),
    "risk of kidney disease": ("কিডনি রোগের ঝুঁকি",),
    "risks": ("ঝুঁকি",),
    "roller bandage": ("রোলার ব্যান্ডেজ",),
    "rosacea": ("রোসেসিয়া", "রোসেসিয়াব্রণ",),
    "roundworms": ("রাউন্ডওয়ার্ম",),
    "runny nose": ("সর্দি",),
    "safe": ("নিরাপদ",),
    "safety": ("নিরাপত্তা",),
    "sarcoidosis": ("সারকোইডোসিস",),
    "scaling": ("স্কেলিং",),
    "scalp": ("মাথার ত্বক",),
    "schedule": ("সময়সূচী",),
    "scheduled dose": ("নির্ধারিত ডোজ",),
    "schizophrenia": ("সিজোফ্রেনিয়া", "স্কিজোফ্রেনিয়া",),
    "scientific evidence": ("বৈজ্ঞানিক প্রমাণ",),
    "scissors": ("কাঁচি",),
    "scoliosis": ("স্কোলিওসিস",),
    "scrapes": ("স্ক্র্যাপ",),
    "scratches": ("আঁচড়",),
    "seasonal affective disorder": ("সিজনাল অ্যাফেক্টিভ ডিসঅর্ডার", "সিজনাল অ্যাফেক্টিভ ডিসঅর্ডার্‌",),
    "seasonal allergies": ("মৌসুমী অ্যালার্জি", "সিজনাল অ্যালার্জি",),
    "seborrhea": ("সেবোরিয়া",),
    "secondary hemorrhage": ("সেকেন্ডারী হেমোরেজ",),
    "secondary hyperaldosteronism": ("সেকেন্ডারি হাইপারালডোস্টেরনিজম",),
    "secretion": ("নিঃসরণ", "নিঃসরণ।",),
    "secretion process": ("ক্ষরণের প্রক্রিয়া।",),
    "secretory cells": ("সিক্রেটরি কোষ",),
    "secretory dynamics": ("সেক্রেটরি ডাইনামিকস",),
    "secretory pattern": ("সিক্রেটরি প্যাটার্ন",),
    "sedation": ("অবসাদ",),
    "sedative": ("উপশমকারী",),
    "sedative effect": ("প্রশমক প্রভাব",),
    "sedatives": ("সেডেটিভ",),
    "seizure disorders": ("খিঁচুনি রোগ",),
    "seizures": ("খিঁচুনি", "সেইজর", "সেজড়স",),
    "sensitivity": ("সংবেদনশীলতা",),
    "sepsis": ("সেপসিস",),
    "sepsis-related hypotension": ("সেপসিস-সম্পর্কিত হাইপোটেনশন",),
    "septic shock": ("সেপটিক শক", "সেপ্টিক শক",),
    "septicemia": ("সেপটিসেমিয়া",),
    "serious side effects": ("গুরুতর পার্শ্বপ্রতিক্রিয়া",),
    "serious symptoms": ("গুরুতর লক্ষণ",),
    "serotonin": ("সেরোটোনিন",),
    "serotonin syndrome": ("সেরোটোনিন সিন্ড্রোম",),
    "serum": ("সিরাম",),
    "serum concentration": ("সিরাম ঘনত্ব",),
    "serum magnesium": ("সিরাম ম্যাগনেসিয়াম",),
    "serum oxt": ("সিরাম ওএক্সটি",),
    "severe abdominal pain": ("পেটে তীব্র ব্যথা",),
    "severe allergic reactions": ("গুরুতর অ্যালার্জি প্রতিক্রিয়া",),
    "severe anxiety": ("গুরুতর উদ্বেগ",),
    "severe bleeding": ("গুরুতর রক্তপাত",),
    "severe cough": ("তীব্র কাশি",),
    "severe drowsiness": ("গুরুতর তন্দ্রা",),
    "severe kidney failure": ("কিডনির গুরুতর দুর্বলতা",),
    "severe or debilitating insomnia": ("গুরুতর বা দুর্বল অনিদ্রা",),
    "severe respiratory distress": ("গুরুতর শ্বাসকষ্ট",),
    "severe sepsis": ("গুরুতর সেপসিস",),
    "sex organs": ("যৌন অঙ্গ",),
    "sex steroids": ("যৌন স্টেরয়েড",),
    "sexual activity": ("যৌন ক্রিয়াকলাপ",),
    "sexual dysfunction": ("যৌন কর্মহীনতা",),
    "sexual orientation": ("যৌন প্রবণতা",),
    "sexually transmitted diseases": ("যৌন রোগ", "যৌনবাহিত  রোগ", "যৌনবাহিত রোগ",),
    "sexually transmitted infections": ("যৌন সংক্রমণ", "যৌন সংক্রামিত সংক্রমণ", "যৌনবাহিত সংক্রমণ",),
    "shampoo": ("শ্যাম্পু",),
    "shigella": ("শিগেলা",),
    "short bowel syndrome": ("শর্ট বাওয়েল সিনড্রোম", "শর্ট বাওয়েল সিন্ড্রোম",),
    "short stature": ("ছোট আকার",),
    "short-term management": ("স্বল্পমেয়াদী ব্যবস্থাপনা",),
    "short-term treatment": ("স্বল্পমেয়াদী চিকিত্সা",),
    "short-term use": ("স্বল্প সময়ের ব্যবহার", "স্বল্পমেয়াদী ব্যবহার",),
    "shortness of breath": ("শ্বাসকষ্ট", "শ্বাসকষ্টে",),
    "sick": ("অসুস্থ",),
    "side effect mitigation": ("পার্শ্বপ্রতিক্রিয়া প্রশমন",),
    "side effects": ("পার্শ্ব প্রতিক্রিয়া", "পার্শ্ব প্রতিক্রিয়াগুলির", "পার্শ্বপ্রতিক্রিয়া", "পার্শ্বপ্রতিক্রিয়া",),
    "single-chain polypeptide": ("একক-চেইন পলিপেপটাইড",),
    "sinus infections": ("সাইনাস সংক্রমণ",),
    "sinuses": ("সাইনাস",),
    "sinusitis": ("সাইনাসের প্রদাহ", "সাইনুসাইটিস", "সাইনোসাইটিস",),
    "skeletal muscle": ("কঙ্কাল পেশী",),
    "skin": ("চর্ম", "চামড়া", "ত্বক",),
    "skin allergies": ("ত্বকের এ্যালার্জি",),
    "skin and mucous membranes": ("ত্বক ও শ্লেষ্মা ঝিল্লি",),
    "skin and skin structure infections": ("ত্বক  ও  ত্বকের  গঠন  সংক্রমণ",),
    "skin and soft tissue": ("ত্বক এবং নরম টিস্যু",),
    "skin and soft tissue infections": ("ত্বক এবং নরম টিস্যু সংক্রমণ",),
    "skin conditions": ("ত্বকের অবস্থা", "ত্বকের অবস্থান",),
    "skin discoloration": ("চামড়াতে বিবর্ন‌তা",),
    "skin diseases": ("চর্মরোগ", "ত্বকের রোগ",),
    "skin disorders": ("ত্বকের ব্যাধি",),
    "skin infection": ("ত্বক সংক্রমণ",),
    "skin infections": ("ত্বকের  সংক্রমণ", "ত্বকের সংক্রমণ",),
    "skin inflammation": ("ত্বকের প্রদাহ",),
    "skin necrosis": ("চামড়ার নেক্রোসিস",),
    "skin pain": ("ত্বকে ব্যথা", "ত্বকের ব্যথা",),
    "skin rash": ("ত্বকে ফুসকুড়ি", "ত্বকের ফুসকুড়ি",),
    "skin reactions": ("ত্বকের প্রতিক্রিয়া",),
    "skin ulcers": ("ত্বকের আলসার",),
    "sleep": ("ঘুম",),
    "sleep apnea": ("স্লিপ অ্যাপনিয়া",),
    "sleep disorders": ("ঘুমের ব্যাধি",),
    "sleep duration": ("ঘুমের সময়কাল",),
    "sleep onset latency": ("ঘুমের সূচনা বিলম্বিতা",),
    "sleep problems": ("ঘুমের সমস্যা",),
    "sleep quality": ("ঘুমের গুণমান",),
    "sleep-related problems": ("ঘুম-সম্পর্কিত সমস্যা",),
    "sleeping": ("ঘুমানো",),
    "slow breathing": ("ধীর শ্বাস",),
    "slow down": ("ধীর করা",),
    "small size": ("ছোট আকার",),
    "smallpox": ("গুটিবসন্ত",),
    "smoking addiction": ("ধূমপান আসক্তি",),
    "smooth muscle": ("মসৃণ পেশী",),
    "sneezing": ("হাঁচি",),
    "social amnesia": ("সামাজিক স্মৃতিভ্রংশ",),
    "social anxiety": ("সামাজিক উদ্বেগ",),
    "social disturbance": ("সামাজিক বিঘ্ন",),
    "social stimulation": ("সামাজিক উদ্দীপনা",),
    "sodium": ("সোডিয়াম",),
    "sodium retention": ("সোডিয়াম ধারণ",),
    "soft tissue": ("নরম টিস্যু",),
    "somatomedin": ("সোমাটোমেডিন",),
    "somatotrope": ("সোমাটোট্রোপ",),
    "somatotroph": ("সোমাটোট্রফ",),
    "somatotroph cells": ("সোমাটোট্রফ কোষ", "সোমাটোট্রফ কোষ।",),
    "somatotroph tumors": ("সোমাটোট্রফ টিউমার।",),
    "somatotrophs": ("সোমাটোট্রফস",),
    "somatotropic cells": ("সোমাটোট্রপিক কোষ",),
    "somatropin": ("সোমাট্রপিন", "সোমাট্রোপিন",),
    "sore throat": ("গলা ব্যথা", "গলায় ব্যথা",),
    "sores in the mouth": ("মুখে ঘা",),
    "sperm": ("শুক্রাণু",),
    "spinal cord": ("মেরুদন্ড",),
    "spinal stenosis": ("মেরুদণ্ডের স্টেনোসিস",),
    "spine": ("মেরুদণ্ড",),
    "splanchnic vessels": ("স্প্ল্যাঞ্চনিক জাহাজে",),
    "spleen": ("প্লীহা",),
    "sports organizations": ("ক্রীড়া সংস্থা",),
    "spray": ("স্প্রে",),
    "standard dose": ("স্ট্যান্ডার্ড ডোজ",),
    "stem cells": ("স্টেম সেল",),
    "steroid hormones": ("স্টেরয়েড হরমোন",),
    "steroidal formation": ("স্টেরয়েডাল গঠন",),
    "steroids": ("স্টেরয়েড",),
    "stevens-johnson syndrome": ("স্টিভেনস-জনসন সিনড্রোম", "স্টিভেনস-জনসন সিন্ড্রোম",),
    "stiffness": ("কঠোরতা",),
    "stimulant-secretion": ("উদ্দীপনা-নিঃসরণ",),
    "stimulated": ("উদ্দীপিত",),
    "stimulation": ("উদ্দীপনা", "উদ্দীপিত",),
    "stomach": ("পাকস্থলি", "পাকস্থলী", "পেট",),
    "stomach ache": ("পেট  ব্যথা", "পেট জ্বালা", "পেট ব্যথা",),
    "stomach cramps": ("পেট ক্র্যাঁক", "পেটে খিঁচুনি",),
    "stomach discomfort": ("পেটের অস্বস্তি",),
    "stomach inflammation": ("পেটে প্রদাহ",),
    "stomach pain": ("পাকস্থলীতে ব্যাথা", "পেট  ব্যথা", "পেট ব্যথা", "পেটে ব্যথা",),
    "stomach ulcer": ("পাকস্থলীর আলসার", "পাকস্থলীর আলসারের", "পেট আলসার", "পেটের আলসার",),
    "stomach ulcers": ("পাকস্থলীর ঘা", "পেটের আলসার",),
    "stomach upset": ("পেটের ব্যাধি",),
    "stomatitis": ("স্টোমাটাইটিস",),
    "stopping medication": ("ঔষধ বন্ধ করা",),
    "strap neck": ("স্ট্র্যাপ গলা",),
    "strength": ("শক্তি",),
    "strep throat": ("স্ট্র্যাপ",),
    "stress": ("মানসিক চাপ", "স্ট্রেস",),
    "stress-induced learning disability": ("চাপজনিত শেখার ক্ষমতার হ্রাস",),
    "stress-related problems": ("স্ট্রেস-সম্পর্কিত সমস্যা",),
    "stroke": ("স্ট্রোক",),
    "stroke or heart attack": ("স্ট্রোক বা হার্ট অ্যাটাকের",),
    "strokes": ("স্ট্রোক",),
    "structural abnormalities of hormones": ("হরমোনের গঠনগত অস্বাভাবিকতা",),
    "structural features": ("কাঠামোগত বৈশিষ্ট্য",),
    "structural lesions": ("কাঠামোগত ক্ষত",),
    "structural properties": ("কাঠামোগত বৈশিষ্ট্য",),
    "structural similarity": ("কাঠামোগত মিল",),
    "subarachnoid hemorrhage": ("সাবরাচনয়েড হেমোরেজ",),
    "subcutaneous tissue": ("ত্বকের নিচের টিস্যু",),
    "substance use disorder": ("পদার্থ ব্যবহারের ব্যাধি",),
    "sudden overdose": ("আকস্মিক ওভারডোজ",),
    "sugar": ("শর্কর",),
    "sugar metabolism": ("শর্করা বিপাক",),
    "sugars": ("শর্করা",),
    "sulfamethoxazole": ("সালফামেথক্সাজোল",),
    "sulfhydryl group": ("সালফাইড্রিল গ্রুপ",),
    "sulfonylureas": ("সালফনিল্যুরিয়া",),
    "superficial bleeding": ("সুপারফিসিয়াল রক্তপাত",),
    "supplement": ("সাপ্লিমেন্ট",),
    "supplements": ("পরিপূরক",),
    "supportive care": ("সাপোর্টিভ কেয়ার",),
    "suppositories": ("সাপোজিটরি",),
    "suppository": ("সাপোজিটর", "সাপোজিটরি",),
    "suppression": ("দমন",),
    "suprachiasmatic nucleus": ("সুপ্রাকিয়াসমেটিক নিউক্লিয়াস",),
    "surgery": ("অস্ত্রোপচার", "অস্ত্রোপচারের", "সার্জারি",),
    "surgical removal": ("অস্ত্রোপচার অপসারণ",),
    "sweat glands": ("ঘর্মগ্রন্থি",),
    "swelling": ("ফোলাভাব",),
    "swelling and inflammation": ("ফুসকুড়ি এবং প্রদাহের", "ফোলা এবং প্রদাহ",),
    "swelling of the face": ("মুখ ফুলে যাওয়া",),
    "swelling of the face or throat": ("মুখ বা গলা ফুলে যাওয়া",),
    "swollen glands": ("ফুলে যাওয়া গ্রন্থি", "ফোলা গ্রন্থি",),
    "sympathetic ganglia": ("সহানুভূতিশীল গ্যাংলিয়া",),
    "sympathetic nervous system": ("সহানুভূতিশীল স্নায়ুতন্ত্র",),
    "symptom relief": ("লক্ষণ উপশম",),
    "symptomatic": ("লক্ষণীয়", "সিম্পটোমেটিক",),
    "symptoms": ("উপসর্গ", "লক্ষণ",),
    "syndrome": ("সিনড্রোম", "সিন্ড্রোম",),
    "synonyms": ("প্রতিশব্দ",),
    "synovitis": ("সাইনােভাইটিস",),
    "synthesis": ("সংশ্লেষণ",),
    "synthesized": ("সংশ্লেষিত",),
    "synthetic": ("সিন্থেটিক",),
    "syringe": ("সিরিঞ্জ",),
    "syrup": ("শিরাপ", "সিরাপ",),
    "syrups": ("সিরাপ",),
    "systemic circulation": ("সিস্টেমিক সঞ্চালন",),
    "systemic diseases": ("সিস্টেমিক রোগ",),
    "systemic embolization": ("সিস্টেমিক এম্বোলাইজেশন",),
    "systemic lupus erythematosus": ("সিস্টেমিক লুপাস এরিথেমাটোসাস",),
    "systolic bp": ("সিস্টোলিক বিপি",),
    "systolic heart failure": ("সিস্টোলিক হার্ট ফেইলিওর",),
    "systolic pressure": ("সিস্টোলিক চাপ",),
    "t cells": ("টি কোষ",),
    "tablet": ("ট্যাবলেট",),
    "tablet or capsule": ("ট্যাবলেট বা ক্যাপসুল",),
    "tablets": ("ট্যাবলেট",),
    "tachycardia": ("টাকাইকার্ডিয়া",),
    "target cells": ("লক্ষ্য কোষ",),
    "teeth": ("দাঁত",),
    "teeth and gums": ("দাঁত ও মাড়ি",),
    "temazepam": ("টেমাজেপাম",),
    "temporary paralysis": ("অস্থায়ী পক্ষাঘাত",),
    "teratogenicity": ("টেরাটোজেনিসিটির",),
    "tertiary hypothyroidism": ("টারশিয়ারি হাইপোথাইরয়েডিজম",),
    "testes": ("টেস্টিস",),
    "testicle": ("টেস্টিকল",),
    "testicles": ("অণ্ডকোষ", "টেস্টিকুল", "শুক্রাশয়",),
    "testicular shrinkage": ("টেস্টিকুলার সংকোচন",),
    "testicular size reduction": ("টেস্টিকুলার আকার হ্রাস",),
    "testis": ("টেস্টিস",),
    "testosterone": ("টেস্টোস্টেরন",),
    "tetany": ("টিটানি",),
    "tetracycline hepatotoxicity": ("টেট্রাসাইক্লিন হেপাটোটক্সিসিটি",),
    "the medicine": ("ওষুধটি",),
    "the patient's heart condition": ("রোগীর হৃদরোগের",),
    "therapeutic": ("থেরাপিউটিক",),
    "therapeutic action": ("থেরাপিউটিক অ্যাকশন",),
    "therapeutic agents": ("থেরাপিউটিক এজেন্ট",),
    "therapeutic response": ("থেরাপিউটিক সাড়া",),
    "therapeutic use": ("থেরাপিউটিক ব্যবহার",),
    "therapy": ("থেরাপি",),
    "thermometer to bp monitor": ("থার্মোমিটার থেকে বিপি মনিটর",),
    "thermoregulation": ("থার্মোরেগুলেশন",),
    "thin skin": ("পাতলা ত্বক",),
    "thiol moiety": ("থিওল ময়েটি",),
    "throat": ("গলা",),
    "throat discomfort": ("গলার অস্বস্তি",),
    "throat infection": ("গলা সংক্রমণ",),
    "throat infections": ("গলা সংক্রমণ",),
    "thrombocytopenia": ("থ্রম্বোসাইটোপেনিয়া",),
    "thromboembolic complications": ("থ্রম্বোএম্বলিক কমপ্লিকেশন",),
    "thromboembolism": ("থ্রম্বোইম্বোলিজম", "থ্রম্বোএম্বোলাইজম",),
    "thrombosis": ("থ্রম্বোসিস",),
    "thrush": ("ঝাপসা",),
    "thymus": ("থাইমাস",),
    "thyroid": ("থাইরয়েড",),
    "thyroid cancer": ("থাইরয়েড ক্যান্সার",),
    "thyroid disease": ("থাইরয়েড রোগ",),
    "thyroid disorder": ("থাইরয়েড ব্যাধি",),
    "thyroid gland": ("থাইরয়েড গ্রন্থি", "থাইরয়েড গ্রন্থি",),
    "thyroid problems": ("থাইরয়েড সমস্যা",),
    "thyroid surgery": ("থাইরয়েড সার্জারি",),
    "thyroid tumor": ("থাইরয়েড টিউমার",),
    "thyroiditis": ("থাইরয়েডাইটিস",),
    "thyrotoxicosis": ("থাইরোটক্সিকোসিস",),
    "time to work": ("কাজ করতে সময়",),
    "tinea": ("টিনিয়া",),
    "tinea corporis": ("টিনিয়া কর্পোরিস",),
    "tinea cruris": ("টিনিয়া ক্রুরিস",),
    "tinea pedis": ("টিনিয়া পেডিস",),
    "tissue": ("টিস্যু",),
    "tissue failure": ("টিস্যুগুলির ব্যর্থতা",),
    "tissue growth": ("টিস্যু বৃদ্ধি",),
    "tissue stimulation": ("টিস্যু উদ্দীপনা",),
    "tissues": ("টিস্যু",),
    "to a doctor or chemist": ("ডাক্তার বা রসায়নবিদকে",),
    "to decay": ("ক্ষয় হওয়া",),
    "to reduce pain": ("ব্যথা",),
    "tocolysis": ("টকোলাইসিস",),
    "tolerating": ("সহ্য করা",),
    "tomax syndrome": ("টোম্যাক্স সিনড্রোম",),
    "tongue": ("জিহ্বা",),
    "tonicity": ("টনিসিটি",),
    "tonsillitis": ("টনসিলাইটিস", "টন্সিলাইটিস", "টন্সিলের প্রদাহমূলক ব্যাধি",),
    "tonsils": ("টনসিল", "টন্সিল",),
    "toothache": ("দাঁত  ব্যথা", "দাঁত ব্যথা",),
    "topical drops": ("টপিকাল ড্রপ",),
    "topical use": ("টপিক্যাল ব্যবহার",),
    "toxemia": ("টক্সেমিয়া",),
    "toxic": ("বিষাক্ত",),
    "traces in urine": ("প্রস্রাবে চিহ্ন",),
    "trachea": ("শ্বাসনালি", "শ্বাসনালী",),
    "tracheitis": ("ট্রাকাইটিস",),
    "tranquilizers": ("ট্রানকুইলাইজার",),
    "transcription": ("ট্রান্সক্রিপশন",),
    "transdermal": ("ট্রান্সডার্মাল",),
    "transgender": ("ট্রান্সজেন্ডার",),
    "transpeptidation": ("ট্রান্সপেপ্টিডেশন",),
    "transplanted organs": ("প্রতিস্থাপিত অঙ্গ",),
    "trauma": ("আঘাত", "ট্রমা",),
    "treated": ("চিকিত্সা",),
    "treatment": ("চিকিত্সা", "চিকিৎসা",),
    "treatment advice": ("চিকিত্সা পরামর্শ",),
    "tremors": ("কম্পন",),
    "trichomoniasis": ("ট্রাইকোমোনিয়াসিস",),
    "triglycerides": ("ট্রাইগ্লিসারাইড",),
    "trimethoprim": ("ট্রাইমেথোপ্রিম",),
    "triple therapy": ("ট্রিপল থেরাপি",),
    "tryptophan": ("ট্রিপটোফ্যান",),
    "tuberculosis": ("যক্ষা",),
    "tubule": ("টিউবুল",),
    "tumor": ("টিউমার", "থাইরয়েড",),
    "tumor cells": ("টিউমার কোষ",),
    "tumors": ("টিউমার",),
    "turner syndrome": ("টার্নার সিন্ড্রোম",),
    "typhoid": ("টাইফয়েড",),
    "typhoid fever": ("টাইফয়েড জ্বর", "টাইফয়েড জ্বর",),
    "tyrosine": ("টাইরোসিন",),
    "ulcer": ("আলসার",),
    "ulcerative colitis": ("অতিস্বনক কোলাইটিস", "আলসারেটিভ কোলাইটিস",),
    "ulcers": ("আলসার",),
    "uncontrolled hypertension": ("অনিয়ন্ত্রিত উচ্চ রক্তচাপ",),
    "unstable angina": ("অস্থির এনজাইনা",),
    "unused medicine": ("অব্যবহৃত ওষুধ",),
    "unusual": ("অস্বাভাবিক",),
    "unusual bleeding or bruising": ("অস্বাভাবিক রক্তপাত বা ক্ষত",),
    "unusual symptoms": ("অস্বাভাবিক উপসর্গ",),
    "upset stomach": ("পেট খারাপ",),
    "uremia": ("ইউরেমিয়া",),
    "urethra": ("মূত্রনালী",),
    "urethral": ("মূত্রনালী",),
    "urinary control": ("মূত্রত্যাগ নিয়ন্ত্রণ",),
    "urinary tract": ("মুত্রনালী", "মূত্রনালি", "মূত্রনালী",),
    "urinary tract infection": ("মূত্রনালী সংক্রমণ", "মূত্রনালীর সংক্রমণ",),
    "urinary tract infections": ("মূত্রনালীর  সংক্রমণ", "মূত্রনালীর সংক্রমণ",),
    "urination": ("প্রস্রাব", "মূত্রত্যাগ",),
    "urogenital tract": ("ইউরোজেনিটাল ট্র্যাক্ট",),
    "urticaria": ("আর্টিকেরিয়া", "আর্টিকেরিয়া",),
    "usual dose": ("স্বাভাবিক ডোজ",),
    "uterine contractions": ("জরায়ু সংকোচন", "জরায়ুর সংকোচন",),
    "uterine muscle tissue": ("জরায়ু পেশী টিস্যু",),
    "uterine problems": ("গর্ভাশয়ের সমস্যা",),
    "uterine rupture": ("ইউটেরাসের বিদারণ",),
    "uterus": ("ইউটেরাস", "গর্ভাশয়", "জরায়ু", "জরায়ু",),
    "vaccine": ("ভ্যাকসিন",),
    "vagina": ("যোনি", "যোনিপথ",),
    "vaginal candidiasis": ("ভ্যাজাইনাল ক্যান্ডিডিয়াসিস",),
    "vaginal dryness": ("যোনি শুষ্কতা",),
    "vaginal inflammation": ("যোনিতে প্রদাহ",),
    "vaginal moniliasis": ("ভ্যাজাইনাল মনিলিয়াসিস",),
    "vaginal yeast infections": ("যোনিতে ইস্ট ঘটিত সংক্রমণ",),
    "valves": ("ভালভ",),
    "vas deferens": ("ভাস ডিফারেন্স",),
    "vascular": ("ভাস্কুলার",),
    "vascular smooth muscle": ("ভাস্কুলার মসৃণ পেশী",),
    "vascular smooth muscle cells": ("ভাস্কুলার মসৃণ পেশী কোষ",),
    "vaso difference": ("ভাস ডিফারেন্স",),
    "vasoconstriction": ("ভাসোকনস্ট্রিকশন",),
    "vasodilation": ("ভাসোডাইলেটেশন",),
    "vasodilatory shock": ("ভাসোডিলেটরি শক",),
    "vasopressin": ("ভাসোপ্রেসিন", "ভ্যাসোপ্রেসিন",),
    "vasospasm": ("ভাসোস্পাজম",),
    "vein": ("শিরা",),
    "veins": ("শিরা",),
    "venous thrombosis": ("শিরার থ্রম্বোসিস",),
    "ventral forebrain": ("ভেন্ট্রাল ফোরব্রেন",),
    "ventricular arrhythmia": ("ভেন্ট্রিকুলার অ্যারিথমিয়া",),
    "ventricular fibrillation": ("ভেন্ট্রিকুলার ফাইব্রিলেশন",),
    "vertebrae": ("কশেরুকা",),
    "vertebrate": ("মেরুদণ্ডী প্রাণী",),
    "vertebrates": ("মেরুদণ্ডী প্রাণী",),
    "vesicle": ("ভেসিকেল",),
    "veterinary medicine": ("ভেটেরিনারি মেডিসিন",),
    "vibration": ("কম্পন",),
    "viral infection": ("ভাইরাল ইনফেকশন",),
    "viral infections": ("ভাইরাল সংক্রমণ",),
    "vision": ("দৃষ্টিভঙ্গি",),
    "vision loss": ("দৃষ্টিশক্তি নষ্ট",),
    "vitamin c": ("ভিটামিন সি",),
    "vitamins": ("বি ভিটামিন", "ভিটামিন",),
    "vomiting": ("বমি", "বমি ভাব",),
    "vomiting blood": ("বমি রক্ত",),
    "von willebrand disease": ("ভন উইলেব্র্যান্ড রোগ",),
    "von willebrand factor": ("ভন উইলেব্র্যান্ড ফ্যাক্টর",),
    "vulvovaginal candidiasis": ("ভালভোভাজিনাল ক্যান্ডিডিয়াসি",),
    "warfarin": ("ওয়ারফারিন", "ওয়ারফেরিন",),
    "warnings": ("সতর্কতা",),
    "water excretion": ("পানির নির্গমন",),
    "water intoxication": ("জলীয় ইনটক্সিকেশন",),
    "watery stools and fever": ("পানির স্টুল এবং জ্বর",),
    "weak corticosteroid": ("দুর্বল কর্টিকোস্টেরয়েড",),
    "weakness": ("দুর্বলতা",),
    "weighing": ("ওজন করা",),
    "weight gain": ("ওজন বৃদ্ধি",),
    "weight loss": ("ওজন হ্রাস",),
    "whipworms": ("হুইপওয়ার্ম",),
    "womb": ("গর্ভ",),
    "worm infection": ("কৃমি সংক্রমণ",),
    "worm infections": ("কৃমি সংক্রমণ",),
    "worm infestation": ("কৃমি উপদ্রব", "কৃমির উপদ্রব",),
    "wound": ("ক্ষত",),
    "wounds": ("ক্ষত",),
    "yeast infection": ("ঈস্ট সংক্রমণ",),
    "yellowing of the skin or eyes": ("ত্বক বা চোখের হলুদাভ বিবর্ণতা",),
    "zinc deficiency": ("জিংকের  ঘাটতি",),
    "zollinger-ellison syndrome": ("জোলিঙ্গার-এলিসন  সিন্ড্রোম", "জোলিঞ্জার-এলিসন সিন্ড্রোম",),
    "zona fascicularis": ("জোনা ফ্যাসিকুলার",),
    "zona glomerulus": ("জোনা গ্লোমেরুলাস",),
}
