import io, collections
from voicerx.translit import transliterate_brand as T
from voicerx.glossary import fold, _TERM_LOOKUP, _DRUG_LOOKUP, _LAB_LOOKUP
from voicerx.brands_india import INDIA_BRANDS

items = list(INDIA_BRANDS.items())[:10000]
gen, skip = {}, collections.Counter()
for brand, generic in items:
    b = T(brand)
    k = fold(b)
    # A key this short matches half the language. MIN is deliberately above
    # the 4 used elsewhere: these are MACHINE-generated, so they get less
    # benefit of the doubt than a hand-written alias.
    if len(k) < 6:
        skip['key under 6 chars'] += 1; continue
    if k in _TERM_LOOKUP:
        skip['collides with a clinical term'] += 1; continue
    if k in _LAB_LOOKUP:
        skip['collides with a lab test'] += 1; continue
    if k in _DRUG_LOOKUP:
        skip['already in the gazetteer'] += 1; continue
    if k in gen and gen[k][1] != generic:
        skip['two brands, one key'] += 1; continue
    gen[k] = (b, generic)

print('brands read      :', len(items))
print('forms accepted   :', len(gen))
for r,n in skip.most_common(): print('   skipped %6d  %s' % (n,r))

out = io.open('voicerx/brands_bengali.py','w',encoding='utf-8')
out.write('# -*- coding: utf-8 -*-\n')
out.write('"""AUTO-GENERATED by tools/gen_bengali_brands.py - do not edit by hand.\n\n')
out.write('Bengali lookup keys for the Indian brand register, produced by RULE\n')
out.write('(voicerx/translit.py), not by a model. These are keys for fold(), never\n')
out.write('display text. Audited on generation against the clinical-term, lab and\n')
out.write('drug tables; anything that collided was dropped rather than shadowing a\n')
out.write('curated entry.\n\nGenerated from the first %d brands.\n"""\n\n' % len(items))
out.write('BENGALI_BRANDS: dict[str, str] = {\n')
for b,g in sorted(gen.values()):
    out.write('    %r: %r,\n' % (b,g))
out.write('}\n')
out.close()
print()
print('sample:')
for b,g in sorted(gen.values())[:6]: print('   %-20s -> %s' % (b,g))
